### ISSUE TITLE
Cookies do not appear to be being sent

### ISSUE THREAD

**Issue by amdprophet** [android-async-http/android-async-http#1]
I created a BasicClientCookie, added it to a PersistentCookieStore, followed by setting the CookieStore in the AsyncHttpClient but the Cookie field does not appear to be set in the request. I'm not sure if I'm missing something.

**Comment by Griffins** [comment]
hello guys. am abit late but i need your help. 
Cookies are not sent to the server. dont know why.
here is my code

private void init() {
        PersistentCookieStore myCookies = new PersistentCookieStore(
                mContext);
        if (mContext == null) {
            Log.d("WebClient", "Warning Context is null. Cookies wont work");
        }

        List<Cookie> cookies = myCookies.getCookies();
        Log.d("WebClient", "Cookies " + cookies.size());
        for (Cookie c : cookies) {
            String cookieName = "";
            String cookieValue = "";
            cookieName = c.getName().toString();
            cookieValue = c.getValue().toString();
            Log.d("WebClient", "Cookie Name:" + cookieName + " Cookie Value: " + cookieValue);
        }
        client.setCookieStore(myCookies);
    }

and here is my logcat

06-06 16:57:57.047  28383-28383/com.spartan D/WebClient﹕ Cookies 0
06-06 16:57:57.048  28383-28383/com.spartan V/WebClient﹕ Sending HTTP POST http://192.168.43.102/fcmapi2/auth
06-06 16:57:57.216  28383-28383/com.spartan D/WebClient﹕ {
    "data": {
    "user_id": "9",
    "username": "test",
    "name": "Griffins Oringo",
    "email": "test@spartanafrica.com",
    "u_id": "A09"
    },
    "code": 200
    }
06-06 16:57:57.224  28383-28383/com.spartan D/WebClient﹕ Cookies 0
06-06 16:57:57.226  28383-28383/com.spartan V/WebClient﹕ Sending HTTP GET http://192.168.43.102/fcmapi2/user
06-06 16:57:57.315  28383-28383/com.spartan D/WebClient﹕ {
    "error": {
    "message": "Invalid Access token.",
    "type": "AuthException",
    "code": 401
    }
    }
when the first request is made the server sends back cookies for authentication on the subsequent requests. but it seems the cookies are not saved. see the cookie count!

**Comment by smarek** [comment]
@Griffins open up a new ticket please, don't append such questions to old tickets.
