### ISSUE TITLE
Making a POST with RequestParams & HttpEntity

### ISSUE THREAD

**Issue by davroux** [android-async-http/android-async-http#1004]
I need to make POST request with a JSONObject into the body.

So for this, I use a StringEntity but I also need to specify a RequestParams.

I don't find any methods to pass these both object. We can only pass a HttpEntity or a RequestParams not both.

How can I do this?

**Comment by sanjayharan** [comment]
I also needs to do same.
I need to post the file object , how can do with entity .

 params.put("fileupload", myFile, "application/gzip");

How can I do with Entity?

StringEntity entity = new StringEntity(jsonObject.toString());

Thanks
