### ISSUE TITLE
v1.4.9 on jCenter

### ISSUE THREAD

**Issue by stephenwoodford** [android-async-http/android-async-http#1034]
Any plans to update the library on jCenter to include the latest version 1.4.9? The last version available there is 1.4.8. Thanks!

**Comment by smarek** [comment]
1.4.x will not be probably updated, as I focus on getting 1.5.x to work and to resolve related issues.

However 1.4.9 is available on Maven Central, https://oss.sonatype.org/content/repositories/staging/com/loopj/android/android-async-http/1.4.9/
Add `mavenCentral()` to `repositories` block in gradle, if you want to use it
