### ISSUE TITLE
Get redirected url ?

### ISSUE THREAD

**Issue by linked67** [android-async-http/android-async-http#1037]
Hi,

Thanks for this nice library !

I need to get some data from a server that redirect to a subdomain that's not aways the same.
The redirect woks fine and i get the datas from TextHttpResponseHandler() but i need the redirected URL.
How can i do this ?

**Comment by linked67** [comment]
I have found a way to catch the Location header but i'm now stuck in a sort of redirect loop that end in a NPE in HttpClient.

    AsyncHttpClient client = new AsyncHttpClient();
    client.setLoggingLevel(Log.ERROR);
    client.setEnableRedirects(true);
    client.getHttpClient().getParams().setParameter(ClientPNames.ALLOW_CIRCULAR_REDIRECTS, true);
    client.setRedirectHandler(new DefaultRedirectHandler() {

			@Override
			public boolean isRedirectRequested(HttpResponse arg0, HttpContext arg1) {
				String redirectURL = arg0.getFirstHeader("Location").getValue();
				return true;
			}
    });


Is it the way to go or is there a more easy way ?

**Comment by zkerhcy** [comment]
I met the same problem, DefaultRedirectHandler is now deprecated, maybe there is a need to provide an API for DefaultRedirectStrategy.
