### ISSUE TITLE
A problem about ResponderHandler

### ISSUE THREAD

**Issue by lengendray** [android-async-http/android-async-http#1039]
```
/**
 * Avoid leaks by using a non-anonymous handler class.
 */
private static class ResponderHandler extends Handler {
    private final AsyncHttpResponseHandler mResponder;

    ResponderHandler(AsyncHttpResponseHandler mResponder, Looper looper) {
        super(looper);
        this.mResponder = mResponder;
    }

    @Override
    public void handleMessage(Message msg) {
        mResponder.handleMessage(msg);
    }
}
```

Usually,in order to avoid leaks when we use Handler,we need to fix our declaration as follows:
1.Declare the Handler as a static class.(you had done it)
2.Use WeakReference for member mResponder.

Shall we do it like this? please show me,thanks!

**Comment by smarek** [comment]
Best coding practices should be discussed on stackoverflow.com
Issues in this project are meant to track bugs and feature requests, not general programming questions.
