### ISSUE TITLE
post request sent as a GET

### ISSUE THREAD

**Issue by ddelizia** [android-async-http/android-async-http#104]
I'm sending a form with post to my web server but my server intercept the request as a GET. I tried to send the same request from a rest client and the server respond correctly so I thing I'm doing something wrong in the android client.

I'm using as a content-type: application/x-www-form-urlencoded is there any way to set this content type?

Here is the code I'm using:

```
    final RequestParams params = new RequestParams();
    params.put(ParamConstants.LOGIN_USERNAME, username);
    params.put(ParamConstants.LOGIN_PASSWORD, password);

    final AsyncHttpClient client = new AsyncHttpClient();

    client.post(URLConstants.MAIN_URL
            + URLConstants.EP_SER_REGISTRATION_login, params,
            new AsyncHttpResponseHandler() {
                @Override
                public void onFailure(final Throwable arg0,
                        final String arg1) {
                    // TODO Auto-generated method stub
                    super.onFailure(arg0, arg1);
                }

                @Override
                public void onFinish() {
                    // TODO Auto-generated method stub
                    super.onFinish();
                }

                @Override
                public void onStart() {
                    // TODO Auto-generated method stub
                    super.onStart();
                }

                @Override
                public void onSuccess(final String response) {
                    Log.i(DataRetriverServiceImpl.class.getSimpleName(),
                            "Data received: " + response);
                    final AccessInfoData accessInfoData = (AccessInfoData) getJsonHandler()
                            .handleJson(response, AccessInfoData.class);
                    if (accessInfoData != null
                            && accessInfoData.isLoggedIn()) {
                        activity.goToMenu();

                    }
                }
            });
```

**Comment by adnanhaider237** [comment]
How did you solved, my server is VPS and i am facing same issue.

**Comment by saeed-rz** [comment]
@adnanhaider237 hi
can you show code?
this doesn't look possible!

**Comment by adnanhaider237** [comment]
> @adnanhaider237 hi
> can you show code?
> this doesn't look possible!

yes sure.
it always go to onFailure and shows fthis error
ERROR: Moved Permanently

RequestParams params = new RequestParams();
params.put("name", et_name.getText().toString().trim());
params.put("sur", et_sur_name.getText().toString().trim());
params.put("uploaded_file", file_name, myFile);
params.put("img", file_name);
AsyncHttpClient client = new AsyncHttpClient();
client.post("url", params,
                                            new TextHttpResponseHandler() {


                                                @Override
                                                public void onFailure(int statusCode, Header[] headers, String responseBody, Throwable error) {

                                                   
                                                    loading.dismiss();
                                                    DialogClass dialog = new DialogClass(context,
                                                            "Warning", s + "Fail to insert in database");
                                                    dialog.show();
                                                }
@Override
                                                public void onSuccess(int statusCode, Header[] headers, String responseString) {
}
});

**Comment by adnanhaider237** [comment]
> @adnanhaider237 hi
> can you show code?
> this doesn't look possible!

and this is My API of PHP.
<?php

    $id = $_POST["id"];
	$name = $_POST["name"];
	$sur = $_POST["sur"];
	$contact =$_POST["contact"];
	$email =$_POST["email"];
	$address =$_POST["address"];
	$note =$_POST["note"];
	$type =$_POST["type"];
	$room =$_POST["room"];
	$town =$_POST["town"];
	$district =$_POST["district"];
	$property =$_POST["property"];
	$link=$_POST["link"];
	$img=$_POST["img"];
	
	
	$file_path = "images/";
	
	require ('connect.php');
	$res = mysqli_query($con,"SELECT * FROM data where name='$name' and sur='$sur' and contact='$contact' and email='$email' and address='$address' and note='$note' and type='$type' and room='$room'  and property='$property'  and town='$town'  and district='$district' and user_id='$id'");
	if ($res->num_rows > 0) {
		echo "2";  
	}
	else{
		$sql = "INSERT INTO data ( name,sur, contact,email, address,note,type,town,district,property,room,user_id,link,status,img) VALUES ('$name','$sur',  '$contact', '$email','$address', '$note','$type','$town','$district', '$property','$room','$id','$link','1','$img')";

		if ($con->query($sql) === TRUE) {
			$file_path = $file_path.basename($_FILES['uploaded_file']['name']);
			if(move_uploaded_file($_FILES['uploaded_file']['tmp_name'],$file_path)){
				echo '1';
			}else{
				echo '0';
			}
			//echo '1';
		} else {
			echo '0';
		}
	}
mysqli_close($con);
?>

**Comment by adnanhaider237** [comment]
> @adnanhaider237 hi
> can you show code?
> this doesn't look possible!

and it work correctly on my localhost by using xamp but on bluehost VPS server this issue occur

**Comment by saeed-rz** [comment]
@adnanhaider237 it seems redirected on some url,
do you have this issue with other post method on your server?

**Comment by adnanhaider237** [comment]
> @adnanhaider237 it seems redirected on some url,
> do you have this issue with other post method on your server?

Yes I am facing on all POST methods on this server.

**Comment by saeed-rz** [comment]
@adnanhaider237 are you using http or https on server?

**Comment by adnanhaider237** [comment]
> @adnanhaider237 are you using http or https on server?

@saeed-rz It is https

**Comment by saeed-rz** [comment]
@adnanhaider237 
i have test client again and no error happen!
can you send me url for debugging purpose?
send it to my email for safety
saeed.rezaei.sa@gmail.com
