### ISSUE TITLE
User-Agent not sent by default

### ISSUE THREAD

**Issue by froismo** [android-async-http/android-async-http#1040]
It appears the User-Agent isn't sent by default to origin
Verified with the Sample App here is logcat:

V/AsyncHttpRH(20875): Progress 192 from 192 (100%)
D/GetSample(20875): Return Headers:
D/GetSample(20875): Server : nginx
D/GetSample(20875): Date : Thu, 03 Dec 2015 18:33:10 GMT
D/GetSample(20875): Content-Type : application/json
D/GetSample(20875): Content-Length : 192
D/GetSample(20875): Connection : keep-alive
D/GetSample(20875): Access-Control-Allow-Origin : *
D/GetSample(20875): Access-Control-Allow-Credentials : true
D/GetSample(20875): Return Status Code: 200
D/GetSample(20875): Response data:
D/GetSample(20875): {
D/GetSample(20875):   "args": {}, 
D/GetSample(20875):   "headers": {
D/GetSample(20875):     "Accept-Encoding": "gzip", 
D/GetSample(20875):     "Content-Length": "0", 
D/GetSample(20875):     "Host": "httpbin.org"
D/GetSample(20875):   }, 
D/GetSample(20875):   "origin": "50.174.236.251", 
D/GetSample(20875):   "url": "https://httpbin.org/get"
D/GetSample(20875): }

**Comment by smarek** [comment]
This is introduced with 1.4.5 version, see CHANGELOG 
`Removed default User-Agent definition from library`

You can use `setUserAgent` API call to set your own, if you wish
