### ISSUE TITLE
Local LAN request times out if no internet

### ISSUE THREAD

**Issue by GRRedWings** [android-async-http/android-async-http#1041]
Has anyone else seen an issue in 1.4.9 where if the device does not have internet access, and is trying to make a web request to a local LAN server it takes a very long time and can timeout?  

We use the library to communicate between a device and a local server, everything works fine as long as the wireless network has internet access.  But if internet access is revoked, the requests take 9-10 seconds.

**Comment by nverbeek** [comment]
I have this issue as well!

**Comment by faizandedia** [comment]
I have the same issue, any solution? this happens after 1.4.9 update I guess

**Comment by nverbeek** [comment]
@faizandedia We were not able to get over this issue, so we switched to [OkHttp](https://github.com/square/okhttp) which does not have this problem, is easier to use and better supported.

**Comment by GRRedWings** [comment]
@faizandedia - I switched to OkHttp as well. I hope they can fix this. We looked into it and I think it has to do with a 3rd party library they are using, but without support for over a month I needed to try something else.

**Comment by faizandedia** [comment]
Thanks,  I will use OkHttp as well. :)

**Comment by matteinn** [comment]
Same issue here.

**Comment by GRRedWings** [comment]
I hate to point people away from one library to another.  But as nverbeek has said earlier, I switched to OkHttp and have not looked back.  No project support for this issue and it's been 4+ months is a red flag for me.

**Comment by matteinn** [comment]
@GRRedWings I totally agree with you. I switched to OkHttp as well after reading the comments and the issue seems to be gone

**Comment by smarek** [comment]
This issue might be solved in 1.5.0. Feel free to re-open if more debug info is provided
