### ISSUE TITLE
Request on LAN error, V1.4.9

### ISSUE THREAD

**Issue by GypsyLife** [android-async-http/android-async-http#1059]
Hey,
While I make a post request to LAN address(like 192.168.1.185),it post to localhost.
This happens on Nexus 4/5/6.I find out the problem in httpclient lib.
Class SchemeSocketFactoryAdaptor, line 65,here u should
invoke connectSocket(Socket, InetSocketAddress, InetSocketAddress, HttpParams)
instead of the deprecated method. 
if u confirm or solve this issue, please comment here.
Thanks for this great lib!

**Comment by GypsyLife** [comment]
I should make it more clearly,on my device (Nexus 5, Android 6.0),InetSocketAddress.getHostName();
returns wrong result "localhost"  for address like 192.168.1.185. Hope this helpfull.

**Comment by flyworkspace** [comment]
I get the same error .I request 10.154.30.52:8081, java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 8081) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused).

**Comment by sendtion** [comment]
I get the same error.
java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 8080) after 3000ms: isConnected failed: ECONNREFUSED (Connection refused).
how to solve it?

**Comment by smarek** [comment]
Questions related to requests to local/ip addresses, that fail, will be tracked under #998
