### ISSUE TITLE
1.5.0-SNAPSHOT jar missing from maven repository

### ISSUE THREAD

**Issue by benadamx** [android-async-http/android-async-http#1102]
I'd like to try the 1.5.0-SNAPSHOT but, per the 1.5.0-SNAPSHOT documentation, no android-async-http-1.5.0-SNAPSHOT.jar is currently available from oss.sonatype.org (and indeed, https://oss.sonatype.org/content/repositories/snapshots/com/loopj/android/android-async-http/ returns 404) - is it available elsewhere?

**Comment by smarek** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/loopj/android/android-async-http/1.5.0-SNAPSHOT/

It has been restored along with development
