### ISSUE TITLE
Compatibility with API <23

### ISSUE THREAD

**Issue by runephilosof** [android-async-http/android-async-http#1103]
On http://loopj.com/android-async-http/ it says "Compatible with Android API 23 and higher".
But in https://github.com/loopj/android-async-http/blob/master/library/build.gradle it says "minSdkVersion 3".
So shouldn't it API 3 and higher on http://loopj.com/android-async-http?

**Comment by TechnoTrancer** [comment]
The lastest version 1.4.9 is just "Compatible with Android API 23 and higher" means that needs "compileSdkVersion 23" or higher (this is because "org.apache.http" classes was deprecated since API 22). But doesn't mean that this is the min Sdk.

**Comment by Akshitha789** [comment]
Hi All,

I have tried through com.loopj.asynchttpclient 1.4.4 and 1.4.6 .. works well on Emulator.. But does throws Connect Timeout error from device - HTC Android 4.4.2 API 19. Any help will be greatly appreciated. Thanks in advance.

org.apache.http.conn.ConnectTimeoutException: Connect to /192.164.1.18:8080 timed out
W/System.err: at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
W/System.err: at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
W/System.err: at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
W/System.err: at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
W/System.err: at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:367)
W/System.err: at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
W/System.err: at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:519)
W/System.err: at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:147)
W/System.err: at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
W/System.err: at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
W/System.err: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err: at java.lang.Thread.run(Thread.java:864)

**Comment by smarek** [comment]
This is addressed with development of 1.5.0 version using custom HttpClient library, instead of system provided one
