### ISSUE TITLE
javax.net.ssl.SSLException

### ISSUE THREAD

**Issue by zhangxx0** [android-async-http/android-async-http#1118]
javax.net.ssl.SSLException: hostname in certificate didn't match: <pic4.zhimg.com> != <_.ucdl.pp.uc.cn> OR <_.ucdl.pp.uc.cn>

How can i do https request with android-async-http?
Thanks!

**Comment by Uphie** [comment]
I also encountered, any ways to solve?

**Comment by dazza5000** [comment]
Anyone find a solution for this? Thank you!

**Comment by Uphie** [comment]
@dazza5000 I haven't solved yet, but I skipped over by replacing "https" with "http" when downloading an image over https.

**Comment by dazza5000** [comment]
I fixed it by creating the client manually (note that this is an insecure way to fix this):

client = new AsyncHttpClient(true,80,443);

**Comment by swh131486** [comment]
这个问题有人解决了吗，我再使用android-async-http-1.4.8，通过https进行传输，也遇到了SSLException: Connection reset by peer问题

**Comment by bhaveshrangani** [comment]
@dazza5000 thanks it works.

**Comment by zung** [comment]
android-async-http-1.4.9 has the same issue,  and i had reduced the version to 1.4.5,  the issue had been solved

**Comment by smarek** [comment]
@zung could you please try with latest 1.4.10, see https://github.com/android-async-http/android-async-http#maven
