### ISSUE TITLE
java.net.UnknownHostException: Unable to resolve host "bogon": No address associated with hostname

### ISSUE THREAD

**Issue by wwiilla** [android-async-http/android-async-http#1122]
Hello everyone, I encountered such a problem. I am use loopj 1.4.9 in my project.

03-02 10:06:14.190 5073-5658/com.loopj.android.http.sample W/System.err: java.net.UnknownHostException: Unable to resolve host "bogon": No address associated with hostname
03-02 10:06:14.190 5073-5658/com.loopj.android.http.sample W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:394)
03-02 10:06:14.190 5073-5658/com.loopj.android.http.sample W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
03-02 10:06:14.190 5073-5658/com.loopj.android.http.sample W/System.err:     at java.net.InetAddress.getByName(InetAddress.java:289)
03-02 10:06:14.190 5073-5658/com.loopj.android.http.sample W/System.err:     at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:154)
03-02 10:06:14.190 5073-5658/com.loopj.android.http.sample W/System.err:     at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
03-02 10:06:14.190 5073-5658/com.loopj.android.http.sample W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
03-02 10:06:14.190 5073-5658/com.loopj.android.http.sample W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
03-02 10:06:14.190 5073-5658/com.loopj.android.http.sample W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-02 10:06:14.195 5073-5658/com.loopj.android.http.sample W/System.err:     at java.lang.Thread.run(Thread.java:841)
How can i fix this problem?

**Comment by tantao900827** [comment]
can you changed you /etc/apt/sources.list?

**Comment by tantao900827** [comment]
or you /etc/hosts is changed?
may be here can help you 
http://askubuntu.com/questions/59458/error-message-when-i-run-sudo-unable-to-resolve-host-none

**Comment by imyar** [comment]
it is a big bug,you said useless

**Comment by smarek** [comment]
Questions related to requests to local/ip addresses, that fail, will be tracked under #998
