### ISSUE TITLE
Static vs. normal HTTP client

### ISSUE THREAD

**Issue by acrolink** [android-async-http/android-async-http#1141]
I see at you pages that you recommend using a static HTTP client, like this:

```
private static AsyncHttpClient client = new AsyncHttpClient();
```

Is this safe to use if I expect my application to initiate POST requests at a rate of 1/second or 1/ per two seconds. Is it safe to use a global static HTTP client like this without losing / skipping some requested HTTP calls? Thanks.

**Comment by smarek** [comment]
It should be safe, if you don't require shared context between those, there should be no issues in using the library like this.
