### ISSUE TITLE
UnknownHostException exception

### ISSUE THREAD

**Issue by isYuriBoyka** [android-async-http/android-async-http#1145]
error:java.io.IOException: UnknownHostException exception: Unable to resolve host "no-data": No address associated with hostname

This is the file I want to download：
http://t-audiop.ubaby.cn/e8325558-9bb1-9524-2f7f-946747583d6d.lrc

Excuse me, what is the reason?

**Comment by imyar** [comment]
i also encounter this bug，waste my three days to find this bug。fuck。i solve this bug by using 1.4.8

**Comment by jordim** [comment]
Solved using version `1.4.8` & useLibrary `org.apache.http.legacy` inside android configuration in your gradle file.

Source: [issues/998#issuecomment-287707807](https://github.com/loopj/android-async-http/issues/998#issuecomment-287707807)

**Comment by smarek** [comment]
Questions related to requests to local/ip addresses, that fail, will be tracked under #998
