### ISSUE TITLE
The type org.apache.http.HttpResponse cannot be resolved. It is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by zhuzhushang** [android-async-http/android-async-http#1149]
The type org.apache.http.HttpResponse cannot be resolved. It is indirectly referenced from required .class files

每次用到这个包，第一行package那里 就会报这个错误

**Comment by smarek** [comment]
This is related to combination of used Android SDK version and library version, these headers are in apache http legacy which was abandoned and later removed from SDK.
Anyway this is too vague issue report, If you provide more debug info, feel free to re-open this ticket.
