### ISSUE TITLE
onFailure(int, Header[], String, Throwable) was not overriden, but callback was received

### ISSUE THREAD

**Issue by ismailqasim** [android-async-http/android-async-http#1150]
I'm creating an app for android in android studio and I'm using android-async-http library for a purpose but I'm getting this error continuously and I don't know why. I've searched up on Internet about this issue but there's no correct solution for this problem.

Here's the full error:

> onFailure(int, Header[], String, Throwable) was not overriden, but callback was received
>                                                                   cz.msebera.android.httpclient.client.HttpResponseException: Not Found
>                                                                       at com.loopj.android.http.AsyncHttpResponseHandler.sendResponseMessage(AsyncHttpResponseHandler.java:446)
>                                                                       at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:160)
>                                                                       at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
>                                                                       at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
>                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
>                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>                                                                       at java.lang.Thread.run(Thread.java:818) 

Here's my code:

> client.post("/acc/login", params, new JsonHttpResponseHandler()
>         {
>             @Override
>             public void onSuccess(int statusCode, cz.msebera.android.httpclient.Header[] headers, JSONObject response) {
>                 try {
>                         log.create(response.getString("message"));
>                         return;
>                 }
>                 catch (JSONException ex)
>                 {
>                     showError("An error occurred while processing data.");
>                 }
>             }
>             @Override
>             public void onFailure(int statusCode, cz.msebera.android.httpclient.Header[] headers, Throwable throwable, JSONObject errorResponse) {
>                 showError("An error occurred while connecting to the server.");
>             }
>         });

**Comment by hogsmate** [comment]
Implement below and it will solve your problem.

 @Override
            public void onFailure(int statusCode,
                                  Header[] headers,
                                  String responseString,
                                  Throwable throwable){
                super.onFailure(statusCode, headers, responseString, throwable);
                showError(responseString);
            }

**Comment by returnvoid** [comment]
Hi

I'm still getting the same error onFailure(int, Header[], String, Throwable) was not overriden, but callback was received org.json.JSONException: Response cannot be parsed as JSON data. 
This is my code:

```
url = new URL(apiUrl + "/login");
RequestParams params = new RequestParams();
params.put("apikey", apiKey);
AsyncHttpClient client = new AsyncHttpClient();
client.post(url.toString(), params, new JsonHttpResponseHandler(){
                @Override
                public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
                    super.onSuccess(statusCode, headers, response);
                    Log.v(TAG, "onSuccess" + response);
                }

                @Override
                public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable){
                    super.onFailure(statusCode, headers, responseString, throwable);
                   Log.v(TAG, "onFailure" + responseString);
                }
            });
```

**Comment by smarek** [comment]
Well there are multiple callbacks named onFailure in 1.4.x library, so you have to override all of them.
Method signature in LogCat should help you with that `onFailure(int, Header[], String, Throwable) `
