### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by AdamMiltonBarker** [android-async-http/android-async-http#1152]
I have seen a few posts in the issues about this but all have been closed which seems strange as the issue is not resolved as far as I can tell. How come the library does not support SNI and has anyone found a work around, I have hit a fairly big road block due to this issue.

Error receiving is as follows:

`hostname in certificate didn't match: <desired host> != <incorrect host> OR <incorrect host> OR <incorrect host>`

**Comment by AdamMiltonBarker** [comment]
I solved this by using a different library

**Comment by singhdd93** [comment]
Is this Lib going to support SNI anytime soon ?
If not Kindly suggest some alternatives as good as this lib

**Comment by toyangel0710** [comment]
This issue should be fixed.
you can use :
AsyncHttpClient asyncHttpClient = new AsyncHttpClient(true, 80, 443)
default it new AsyncHttpClient(false, 80, 443)

**Comment by smarek** [comment]
SNI feature will be solved in #991, closing this as duplicate
