### ISSUE TITLE
ClientProtocolEception & Circular Redirect

### ISSUE THREAD

**Issue by ksparakis** [android-async-http/android-async-http#1160]
Hello, In my android application I have 1 activity that loads data.
so for example 

login -> load data activity -> whatever other activity.

when I return back to the Load Data Activity.

Note I have tried playing around with the activity stack as my initial thoughts where the possibility of the activity already running in the background could be messing this up. But I have still yet to find a solution.

 I get the following error from loopj:

> V/AsyncHttpRH: Request retry no. 1
> V/AsyncHttpRH: Request retry no. 2
> V/AsyncHttpRH: Request retry no. 3
> V/AsyncHttpRH: Request retry no. 4
> V/AsyncHttpRH: Request retry no. 5
> W/System.err: cz.msebera.android.httpclient.client.ClientProtocolException
> W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
> W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
> W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
> W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
> W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
> W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
> W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> W/System.err:     at java.lang.Thread.run(Thread.java:841)
> W/System.err: Caused by: cz.msebera.android.httpclient.client.CircularRedirectException: Circular redirect to 'https://fakeurl.com/api'
> W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRedirectStrategy.getLocationURI(DefaultRedirectStrategy.java:174)
> W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRedirectStrategy.getRedirect(DefaultRedirectStrategy.java:217)
> W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.handleResponse(DefaultRequestDirector.java:1084)
> W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:515)
> W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
> W/System.err:   ... 9 more

**Comment by jiqishou** [comment]
Did you find any solution for this problem? I got the same issue.

**Comment by jiqishou** [comment]
Got it. This will make it works.

client.setEnableRedirects(true);

**Comment by ksparakis** [comment]
@jiqishou THANK YOU! been at this for way too long. How did you figure it out in an hour?

**Comment by jiqishou** [comment]
Just googled it. :)

**Comment by smarek** [comment]
@jiqishou correct answer, closing as solved
