### ISSUE TITLE
RequestParams not allow same value on the same key

### ISSUE THREAD

**Issue by azizimusa** [android-async-http/android-async-http#1162]
I need to make my post request to follow html form input.

`<input type="text" name="studentSeqId" value="155"><br/>`
    `<input type="text" name="attendanceStatus" value="20"><br/>`
    `<input type="text" name="studentSeqId" value="33"><br/>`
    `<input type="text" name="attendanceStatus" value="20"><br/>`
    `<input type="text" name="studentSeqId" value="338"><br/>`
    `<input type="text" name="attendanceStatus" value="20"><br/>`
    `<input type="submit" name="submit">`

When Im doing this 

`RequestParams params = new RequesParams();`

`for (AttendanceUpdate get : getAttendanceUpdate()) {`
`params.add("studentSeqId", String.valueOf(get.seqId));`
`params.add("attendanceStatus", String.valueOf(get.attendanceStatus));`
        `}`

and then, when I post. Only parameter with the unique value is posted. Since **studentSeqId** number is all unique, all **studentSeqId** is posted, but only 1 **attendanceStatus** is posted. Because **attendanceStatus** is same value. 

Even though they are the same value, but I really really need to make them posted.

**Comment by smarek** [comment]
See docs for RequestParams here https://android-async-http.github.io/android-async-http/doc/com/loopj/android/http/RequestParams.html

From my point-of-view, you can use only ordered collection, which is in docs listed as
```
 List<String> list = new ArrayList<String>(); // Ordered collection
 list.add("Java");
 list.add("C");
 params.put("languages", list); // url params: "languages[0]=Java&languages[1]=C"

 String[] colors = { "blue", "yellow" }; // Ordered collection
 params.put("colors", colors); // url params: "colors[0]=blue&colors[1]=yellow"
```

That should solve your problem
