### ISSUE TITLE
Cannot send JSON thought StringEntity using POST

### ISSUE THREAD

**Issue by Manck** [android-async-http/android-async-http#1163]
Hi, I send a couple of messages via email and other ways, but I believe this is the right medium to ask this question. 
I few months ago I used the version 1.4.4 to send JSON using POST and StringEntity. But now this seems to be different, as post does not uses StringEntity anymore. What's the new way to achieve this?

Thank you.

This is the way I used before:
        JSONObject json = new JSONObject();

```
    try {
        json.put("password", password);
        json.put("correo", email);

        StringEntity entity = new StringEntity(json.toString(), HTTP.UTF_8);
        entity.setContentType("application/json");

        AsyncHttpClient client = new AsyncHttpClient();

        client.post(this, "http://192.168.10.66:8080/useraccountPost3/post/dopost", entity, "application/json",
                new AsyncHttpResponseHandler() {
                    @Override
                    public void onSuccess(String estado) {
                        Log.d("HTTP", "OK");
                        doSomething();
                    }
                    @Override
                    public void onFailure(int statusCode, Throwable error,
                                          String content) {
                        Toast.makeText(getApplicationContext(), "error", Toast.LENGTH_SHORT).show();
                        Log.d("HTTP", "onFailure: " + statusCode);
                    }
                });
```

**Comment by azizimusa** [comment]
I use like this, working for me.

    private void fetchProfile(final String result) {

        JSONObject j = new JSONObject();
        try {
            j.put("uacc_id", result);
        } catch (JSONException e) {
            e.printStackTrace();
        }


        try {
            RestClient.post("/getprofile", mContext, new StringEntity(j.toString()), new JsonHttpResponseHandler() {
                @Override
                public void onSuccess(int statusCode, Header[] headers, JSONObject response) {

                    Timber.e(response.toString());

                    if (response.optInt("status") == 1) {
                        replaceFragment(Profile.newInstance(result));
                    } else {
                        showSnack(view, "User not exist", Snackbar.LENGTH_LONG);
                    }
                }

                @Override
                public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONObject errorResponse) {
                    Timber.e(throwable.toString());
                }
            });
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    } 

    public RequestHandle post(String url, Context context, HttpEntity entity,      AsyncHttpResponseHandler responseHandler) {
        Timber.e(entity.toString());
        return client.post(context, getAbsoluteUrl(url), entity, null, responseHandler);
    }

**Comment by smarek** [comment]
@azizimusa suggestion is correct in my opinion and no response from author, closing this ticket for inactivity
