### ISSUE TITLE
FileAsyncHttpResponseHandler return 304 not modified

### ISSUE THREAD

**Issue by sannysinghs** [android-async-http/android-async-http#1165]
First of all not sure whether it is server and client side issue. Images were uploaded to AWS S3 server and client need to downlaod image immediately when it is updated . 

```
httpClient.addHeader("If-Modified-Since", lastModified); // add Last-Modified based on cache last-modified

httpClient.head(task.url, new AsyncHttpResponseHandler() { 
   // if modified date from server is larger than my local last modified date 
   // will download new image by using client.get() as below

   httpClient.get(task.url,
                        new FileAsyncHttpResponseHandler(Application.getInstance()) {
                           //here i got 304 status and in onFailure() , it says **not-modified**  
                       });
})
```

In above calls , calling **head** method return correctly if the server update image but in **get** where i download the image , it always return **304** with **not modified**

really not sure what is going under the hood. i found similar issue [here](https://github.com/loopj/android-async-http/issues/22). But doesnt' seem to understand that much . Thanks

**Comment by smarek** [comment]
Such issues, unless you've got any hint it's issue of library, should be discussed on stackoverflow.com
