### ISSUE TITLE
1.4.9 ConnectTimeoutException when connect to a LAN IP like http://192.168.2.144:8080/

### ISSUE THREAD

**Issue by leafisme** [android-async-http/android-async-http#1166]
cz.msebera.android.httpclient.conn.ConnectTimeoutException: Connect to bogon/218.93.250.18:8080 timed out

in webview is ok, when back to version 1.4.5  it works fine!

**Comment by TLHP** [comment]
Any update for this issue? We have the same problem ...

**Comment by balkarov** [comment]
+1

**Comment by cugxy** [comment]
+1

**Comment by smarek** [comment]
Questions related to requests to local/ip addresses, that fail, will be tracked under #998
