### ISSUE TITLE
How to input data from server in a MAP  

### ISSUE THREAD

**Issue by oscarcuenca** [android-async-http/android-async-http#1169]
Hi 
I am using loopj for a process of register and login. It is working really good with very short code, I am traying to take some data from the response of my server but after traying many ways , all the time I get message that values are empty, so it means I am making worng. I would appreciate if anyone can help me about how to do it.  Here I am not detailing the way to get data that I have been traying to implement since I tried many ways, so only I detail the code which is working correctly:
My current code is giving me back in "responseStr":
`I/APP: onSuccess: loopj {
                                          "estado": 1,
                                          "ususrio": {
                                              "user_name": "oscar cuenca",
                                              "user_email": "oscarcuenca2@hotmail.com",
                                              "claveApi": "a3140b7a8f6bb6f3475e6fec743e4dcd"
                                          }
                                      }`

And my current code is;
` RequestHandle post = client.post(this, LOGIN_URL, entity, "application/json", new AsyncHttpResponseHandler() {
            @Override
            public void onStart() {
                // called before request is started
            }

```
        @Override

        public void onSuccess(int statusCode, Header[] headers, byte[] response) {
            // called when response HTTP status is "200 OK"
            String responseStr = null;
            try {
                responseStr = new String(response, "UTF-8");

            } catch (UnsupportedEncodingException e1) {
                e1.printStackTrace();
            }
            Log.i(UtilitiesGlobal.TAG, "onSuccess: loopj " + responseStr);

            Toast toast1 =
                    Toast.makeText(getApplicationContext(),
                            R.string.Logeo_exitoso, Toast.LENGTH_LONG);

            toast1.show();
            Intent intent = new Intent(Login.this, ProfileActivity.class);
            startActivity(intent);
        }

        @Override
        public void onFailure(int statusCode, Header[] headers, byte[] errorResponse, Throwable e) {
         ........}`
```

Specially I am interested in getting "Apikey" which is "claveApi". from the three values retorned.
Thanks in advance,

**Comment by cseebregts** [comment]
To retrieve the `claveApi` from the `responseStr`, add the following method:
        
    private String getApiKey(String json) throws JSONException {
        JSONObject jsonObj = new JSONObject(json);
        JSONObject ususrioJsonObj = jsonObj.getJSONObject("ususrio");
        return ususrioJsonObj.getString("claveApi");
    }

Example usage within `onSuccess` method:

    String responseStr = null;
    try {
        responseStr = new String(response, "UTF-8");
        String apiKey = getApiKey(responseStr);
    } catch (JSONException e) {
        e.printStackTrace();
    } catch (UnsupportedEncodingException e1) {
        e1.printStackTrace();
    }

**Comment by smarek** [comment]
@cseebregts code seems OK to me, and no response from oscar, so i presume this issue is solved.
