### ISSUE TITLE
HTTP Status 415

### ISSUE THREAD

**Issue by geogie** [android-async-http/android-async-http#1170]
Post请求
 请求参数：RequestParams params = new RequestParams();
                params.put("type_col", "ARTICLE_TYPE");
                params.put("userId", "ccfb1fa802bf4cb3b5d0d66240252aaf");
                params.put("objId", "6397c8842b1d40bf8d4bd18e01f3490e");
访问地址：http://101.200.136.131:8080/quintessenceData/mcm/api/collection_tab/
返回错误：415码
<html><head><title>Apache Tomcat/7.0.62 -
Error report</title><style></style> </head><body><h1>HTTP Status 415 -
</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p>
<p><b>message</b> <u></u></p><p><b>description</b>
<u>
The server refused this request because the request entity is in a format not supported by the requested resource for the requested method.
</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.62</h3></body></html>

**Comment by smarek** [comment]
Missing debug info, code looks OK to me. If you provide more debug info, feel free to re-open this ticket.
Also this doesn't seem to be issue in library, more like backend issue
