### ISSUE TITLE
Uploading progress

### ISSUE THREAD

**Issue by voidberg** [android-async-http/android-async-http#118]
Hey,

When uploading files to the server, is there a way I can have a callback to see the progress of the upload?

Thanks

**Comment by sizrar** [comment]
@hmedat2008 @nadam Highly possible that the server doesn't give a proper "Content-length" value in the headers ? I had the same issue with a varnish in front of an apache that was removing some headers by misconfiguration...

**Comment by smarek** [comment]
@sizrar if you have issue please open new ticket, this one is back from 2014
Closing for obsoleteness
