### ISSUE TITLE
send request params in an order 

### ISSUE THREAD

**Issue by kprathap23** [android-async-http/android-async-http#1181]
I have params like below
 params.put("address1", address1);
    params.put("address2", address2);
        params.put("address3", address3);
        params.put("postcode", postcode);
        params.put("city", city);
        params.put("state", state);
        params.put("email", email);
        params.put("gender", gender);

I want to send this params in this order only in , the request changes the order everytime i send new request.

```
     AsyncHttpClient client = new AsyncHttpClient();
    client.post(activity, URL , params, new JsonHttpResponseHandler() {
        @Override
        public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
            activity.hideLoading();
         }
     }
```

**Comment by AroraAsh** [comment]
You could convert your data into a string and then send it as a http entity.
This would ensure data is sent in the order you require in.
refer this link - http://stackoverflow.com/questions/13052036/posting-json-xml-using-android-async-http-loopj

**Comment by smarek** [comment]
@AroraAsh is correct with suggestion, and see relevant response to similar ticket https://github.com/android-async-http/android-async-http/issues/1156#issuecomment-495248060
