### ISSUE TITLE
statusCode=400, Bad Request

### ISSUE THREAD

**Issue by sendtion** [android-async-http/android-async-http#1183]
statusCode=400，error=cz.msebera.android.httpclient.client.HttpResponseException: Bad Request

Part of the interface has this problem
Part of the interface is normal
This is why? how to solve the problem

**Comment by smarek** [comment]
1.4.x will not be probably updated, as I focus on getting 1.5.x to work and to resolve related issues.
Mentioned issue should be already solved in 1.5.0-SNAPSHOT release
