### ISSUE TITLE
cancelRequestsByTag doesn't work unless Context provided in GET request

### ISSUE THREAD

**Issue by qvk** [android-async-http/android-async-http#1184]
I was testing cancelling asynchronous requests started by a `AsyncHttpClient`. When I use the `get()` method without the context, 

`mClient.get(url, new AsyncHttpResponseHandler{...}).setTag("myTag");`

the request cannot be cancelled using the `cancelRequestsByTag()` method.

`mClient.cancelRequestsByTag("myTag", true) // doesn't work`

However, when I use the `get()` method with context,

`mClient.get(SomeActivity.this, url, new AsyncHttpResponseHandler{...}).setTag("myTag");`

the request is successfully cancelled using the `cancelRequestsByTag()` method. The progress callback stops, `onCancel()` callback is received and I also see a log 

> V/AsyncHttpRH: Request got cancelled

None of this happens in the previous case.

I wonder if this behavior is intended or not. Because there is already a mechanism to set context (using the `get()` method) and cancel such requests using the `cancelRequests(Context context, boolean mayInterruptIfRunning)` method (this also works without any problems). So, in a way cancelling requests by using the context as a TAG. So, why is a request started with a context required if I am already setting a TAG on the requestHandle?

**Update:** Using the RequestHandle.cancel() method works whether using the get() method with Context argument or not.

I intend to use this android-async-http library in my own android library where I may not have access to any Context. 

Please suggest if there is a way to start and cancel requests without involving Context and also if the behavior described above is intended or a bug. Thanks.

Using library version 1.4.9

**Comment by MoonlightAniki** [comment]
get/post method without passing context parameter can't be cancelled , if  you dont want pass activity context , you can pass application context, then you can cancel the request with cancelRequestsByTAG

**Comment by smarek** [comment]
@MoonlightAniki provided correct answer, thank you for that
