### ISSUE TITLE
Connecting to wrong machine when using IP

### ISSUE THREAD

**Issue by AliA74** [android-async-http/android-async-http#1185]
Hello,

We were having a really strange issue in our app . We were trying to connect to our server which doesn't have a domain thus we were reaching it by IP. But it was strange we were connecting to some wrong machine ! We could establish correct connection using a browser on the device but not with the library .

This is the address we were trying to reach (Which you can test it):
http://164.138.19.117/v1/version

if you get {"status":"failed","message":"Security Error"} then it means you have successfully reached the correct machine but if you get any other response (as we were getting 404 Not Found) it means you have reached wrong machine.

We switched to another library for this particular server and it's working correctly now.

I hope you will find this useful and can make a fix around this.

P.S. We were using version 1.4.9 , Not on all devices we had problem but most of them

**Comment by ViteRoberto** [comment]
Do you find any solution? I got the same problem.

**Comment by AliA74** [comment]
@ViteRoberto Nope , I just ended up using another library(OkHttp) .

**Comment by ViteRoberto** [comment]
Thankyou so much

**Comment by bilthon** [comment]
This is also happening here, I just issued a POST request for IP: 138.68.30.50 and could check (using wireshark) that the library is actually sending it to 191.101.3.82.

**Comment by bilthon** [comment]
This only happens with the latest release 1.4.9. I went back to 1.4.8 and it just worked.

**Comment by smarek** [comment]
Questions related to requests to local/ip addresses, that fail, will be tracked under #998
