### ISSUE TITLE
cz.msebera.android.httpclient are try to connect thridpart host 120.192.83.163.

### ISSUE THREAD

**Issue by about-bob** [android-async-http/android-async-http#1194]
java.net.ConnectException: failed to connect to bogon/120.192.83.163 (port 7080) after 120000ms: isConnected failed: ECONNREFUSED (Connection refused)
08-12 11:27:45.493 10718-11679/xxxx.com W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:224)
08-12 11:27:45.493 10718-11679/xxxx.com W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
08-12 11:27:45.493 10718-11679/xxxx.com W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:112)
08-12 11:27:45.493 10718-11679/xxxx.com W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
08-12 11:27:45.493 10718-11679/xxxx.com W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
08-12 11:27:45.493 10718-11679/xxxx.com W/System.err:     at java.net.Socket.connect(Socket.java:842)
08-12 11:27:45.493 10718-11679/xxxx.com W/System.err:     at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
08-12 11:27:45.493 10718-11679/xxxx.com W/System.err:     at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:157)
08-12 11:27:45.501 10718-11679/xxxx.com W/System.err:     at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
08-12 11:27:45.501 10718-11679/xxxx.com W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
08-12 11:27:45.501 10718-11679/xxxx.com W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
08-12 11:27:45.501 10718-11679/xxxx.com W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
08-12 11:27:45.501 10718-11679/xxxx.com W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
08-12 11:27:45.501 10718-11679/xxxx.com W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
08-12 11:27:45.501 10718-11679/xxxx.com W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
08-12 11:27:45.501 10718-11679/xxxx.com W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
08-12 11:27:45.501 10718-11679/xxxx.com W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)

**Comment by about-bob** [comment]
https://github.com/loopj/android-async-http/blob/1.4.9/CHANGELOG.md
`IMPORTANT, We've switched library from using org.apache.http to use cz.msebera.android.httpclient, you have to update all your code`

**Comment by smarek** [comment]
Questions related to requests to local/ip addresses, that fail, will be tracked under #998
