### ISSUE TITLE
can't resolve symbol 'cz'

### ISSUE THREAD

**Issue by TedYt** [android-async-http/android-async-http#1195]
I add this ‘import com.loopj.android.http.*;’
However, this method:
public void onSuccess(int statusCode, cz.msebera.android.httpclient.Header[] headers, byte[] responseBody) {
                Log.d("tui", "baidu Response success");
            }

there is an error saying:　can't resover symbol 'cz'

**Comment by smarek** [comment]
@junweipan correct answer, thank you
