### ISSUE TITLE
Django compatibility

### ISSUE THREAD

**Issue by pkyad** [android-async-http/android-async-http#1196]
Hi all,

I am working with Django based backend server where when you successfully hit the **http://server/login** with a post request containing username and password it will respond with a header to set csrf cookie and session ID.

The problem is if I am doing this from a browser it works (the header to set csrf and session is coming ) but when I am hitting it using android-async-http , the server is providing me only csrf token only but not the session ID.

Is it something related to client agent ?

**Comment by smarek** [comment]
Django is unrelated, as http server it should work with this library out-of-the-box
Issues in this project are meant to track bugs and feature requests, not general programming questions.
