### ISSUE TITLE
SNI is broken in android-async-http even though it was fixed in smarek's httpclient

### ISSUE THREAD

**Issue by ApoorvKhatreja** [android-async-http/android-async-http#1201]
Reference: https://github.com/smarek/httpclient-android/issues/7

The android-async-http library uses an older version of @smarek httpclient  (4.3.6) while the latest version (4.4.1.2) fixes the SNI issue. Fixing this would also require moving off of the deprecated `SSLSocketFactory` class and switching to the new `SSLConnectionSocketFactory` class which has the fix.

**Comment by MIkeeJY** [comment]
Just try okhttp instead of this lib :)

**Comment by smarek** [comment]
SNI feature will be solved in #991, closing this as duplicate
