### ISSUE TITLE
Please remove synthetic methods

### ISSUE THREAD

**Issue by RiteshChandnani** [android-async-http/android-async-http#1219]
There’s no true nesting in Java. Hence, any access to private members of outer class from nested class will have to go via a package scoped method generated by Java to facilitate the call.

To reduce method, make methods of outer class package scoped.

More information:
https://realm.io/news/360andev-jake-wharton-java-hidden-costs-android/

**Comment by smarek** [comment]
Well without context or points where in the library/sample-app you suggest changes, I'm unable to provide any feedback.
