### ISSUE TITLE
API 23, client doesn't work at all! Useless :(

### ISSUE THREAD

**Issue by Shunajlov** [android-async-http/android-async-http#1221]
When server was unavailable trhu domain, i got an error like "Circular redirect to '<some URL>'.
But when i used this url, nothing happend. 
No errors, no calling onSuccess or OnFailure method. 
Server responces with JSON Objects.
I used JsonHttpResponseHandler as a handler, and AsyncHttpResponseHandler - it doesn't matter. 
I called get-requests to server. 

My device is Samsung Galaxy S7 Edge with Android 6.0 (API 23), now i don't have a chance to check it with other API levels. But i need it also to work with API 23. 

Please, help, if you can. 
Thanks!

Best wishes, Alexander!

**Comment by saeed-rz** [comment]
your server url is static or redirect in server side?
for ex your server load on "https" and redirect "http" to "https", and u call "http" version from client

**Comment by Shunajlov** [comment]
Customer has a test server, i need to get JSON answer from GET response, for example, URL:
http://178.161.171.41:10080/mcc/hs/offer/getoffers/test?code=6008&idmobile=dd30e75ebf5772b5
In browser, first, i see HTTP status 200 - OK and responce body, but after that in Network Tab in Google Chrome i can see a lot of redirections. 
The last one has status 204 without any responce body... 
Don't know how to get the first result i need. Is there a way for me to determine that it is server-side problem or client-side?

**Comment by saeed-rz** [comment]
i have checked this url http://178.161.171.41:10080/mcc/hs/offer/getoffers/test?code=6008&idmobile=dd30e75ebf5772b5 and dont see any redirection!

**Comment by Shunajlov** [comment]
Mb they have fixed it, i'll check it tommorow.

**Comment by MrshaoGx** [comment]
it doesn't work man....version:1.4.9.. only for android 7.0+

**Comment by smarek** [comment]
Use 1.4.8 or wait for 1.5.0, sorry 'bout that

**Comment by gxshao** [comment]
> Use 1.4.8 or wait for 1.5.0, sorry 'bout that

That was took so long haha
