### ISSUE TITLE
different behaviour debug <-> release

### ISSUE THREAD

**Issue by flaushi** [android-async-http/android-async-http#1222]
Hi guys, 
i am testing on an API 22 device here, and facing trouble with code that worked fine until now:

    RequestParams paramsRegister = new RequestParams();
    paramsRegister.put("serial", key);
    paramsRegister.put("test", "again");
    prepareParams(params);
    Log.d(TAG, "params " + params.toString());

my prepareParams function adds standard information:

    private void prepareParams (RequestParams params) {
        addKeyValue(params, "type", BuildConfig.FLAVOR.toLowerCase());
        addKeyValue(params, "appversion", BuildConfig.APPLICATION_ID);
    }

    private void addKeyValue(RequestParams params, String key, String value) {
		if(key.length() > 0 && ! params.has(key)) {
			params.put(key, value); //LINE X
		}
    }
The output only is "test= again&serial=xxx", so it seems like prepareParams is not called at all. However I traced that down completely, and everything is called on my side as it should. However, params.toString() before and after LINE X give the same result.

I have the same function for putting ints, it works fine. But for putting String-String kv-pairs, it fails. If I instead use RequestParams.add, it also works.

Note: This only happens on this API 22 device, and only in debug mode! In release builds, putting of Strings does work (but I cannot debug this so easily, but it does work). Am I missing something?

Here is my build.gradle:

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"
    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        applicationId "xxx"
        minSdkVersion 15
        versionCode 85
        versionName "3.3.5"
    }
dependencies {
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true
    }
    compile 'com.android.support:support-v4:23.3.0'
    compile 'com.android.support:palette-v7:23.3.0'
    compile "com.android.support:recyclerview-v7:23.3.0"
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.facebook.android:facebook-android-sdk:4.8.0'
    compile 'com.google.android.gms:play-services-analytics:9.6.1'
    compile 'com.google.android.gms:play-services-location:9.6.1'
    compile 'com.google.firebase:firebase-core:9.6.1'
    compile 'com.google.android.gms:play-services-ads:9.6.1'
    compile "com.google.firebase:firebase-messaging:9.6.1"
    compile 'com.google.zxing:core:3.2.0'
    compile 'com.journeyapps:zxing-android-embedded:3.0.3@aar'
    compile 'org.apmem.tools:layouts:1.10@aar'
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'org.apache.commons:commons-lang3:3.4'
    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
}
Thank you guys in advance!

**Comment by smarek** [comment]
I'm sorry, but this looks like issue of your development/debug environment, because of what you've described. Cannot help you with that
