### ISSUE TITLE
Request to local server over WiFi fails

### ISSUE THREAD

**Issue by dominikbielinski** [android-async-http/android-async-http#1225]
My PC and Android are both connected to same WiFi. I have some webservices running on PC. When requesting them from android with IP like '192.168.1.2:8080' it fails with 
java.net.ConnectException: failed to connect to netiabox.netia.dom/192.168.1.254 (port 8080) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused) (192.168.1.254 is default gateway).
When I request my service from any browser on android it successfully connects to PC (well it says method not supported, because webservice is post, but at least it finds the server).
When switching on android from WiFi to normal data usage (like 4G) and requesting my webservice through external IP like 77.254.XXX.XX:8080 the request is successful. 
Changing port to any other, eg. 8084 results in same error. 
Increasing timeout of the request does not help either.

**Comment by smarek** [comment]
This is not issue of the library.
