### ISSUE TITLE
how do i implement a function like CyclicBarrier

### ISSUE THREAD

**Issue by silenceyear** [android-async-http/android-async-http#1230]
i have called several requests,i don't care about the callback order,but want to do something after all requests have callbacked just like CyclicBarrier.i created CyclicBarrier and called CyclicBarrier.await() after each callback,but it didn't work,some request(maybe onSuccess callback) even don't execute.

`CyclicBarrier barrier = new CyclicBarrier(5, new Runnable() {
                                @Override
                                public void run() {
                                    Log.i("CloudSyncTaskService", "CyclicBarrier: done！");
                                }
                            });
                            requestBaseArgsSet(wcuSn,barrier);//AsyncHttpClient request
                            requestAdvArgsSet(wcuSn,barrier);
                            requestCollectData(wcuSn,barrier);
                            requestDeviceEvent(wcuSn,barrier);
                            requestDeviceAlert(wcuSn,barrier);`

**Comment by smarek** [comment]
Best coding practices should be discussed on stackoverflow.com
Issues in this project are meant to track bugs and feature requests, not general programming questions.
