### ISSUE TITLE
java.lang.AssertionError: Cannot create parent directories for requested File location

### ISSUE THREAD

**Issue by annhosue2116** [android-async-http/android-async-http#1232]
Caused by java.lang.AssertionError: Cannot create parent directories for requested File location
       at com.loopj.android.http.Utils.asserts(SourceFile:39)
       at com.loopj.android.http.FileAsyncHttpResponseHandler.(SourceFile)
       at com.loopj.android.http.FileAsyncHttpResponseHandler.(SourceFile)

I  use verion is 1.4.8, and It not any phone.

My Code below:

                RequestHandle requestHandle = httpClient.getHttpClient().get(context,
					myAction.getServerLink(),
					new FileAsyncHttpResponseHandler(myAction.getTempFile(),
							false) {

						@Override
						public void onFailure(int status, Header[] headers,
								Throwable error, File file) {
						}

						@Override
						public void onSuccess(int status, Header[] headers,
								File file) {
						}

						@Override
						public void onProgress(long bytesWritten, long totalSize) {
							}
						}

					});

is this solved over 1.4.8 ?

**Comment by smarek** [comment]
Well if you cannot create directories in provided target directory, that is not something the library could solve. You might want to check the permissions / available storage before making such request
