### ISSUE TITLE
UnknownHostException: Unable to resolve host "nsg-static-243.21.71.182.airtel.in": No address associated with hostname

### ISSUE THREAD

**Issue by shivchauhan09** [android-async-http/android-async-http#1233]
I am using loopj for communication of android mobile app to the server.
i am getting error like this:-
 W/System.err: java.net.UnknownHostException: Unable to resolve host "nsg-static-243.21.71.182.airtel.in": No address associated with hostname

Please suggest me what  the exact problem is?

Here is my url:-
http://182.71.21.243/apnikheti/apnikhetiapp/getCategory.php

Its working fine on browser, on POstman, online rest debugger, hurl it, even in the app using other libraries.
Please help me out.

**Comment by Tindi** [comment]
Hi @shivchauhan09 did you manage to find a solution? I get the same when I upgraded to version 1.4.9

**Comment by saintfalcon** [comment]
Same here on 1.4.9

**Comment by jordim** [comment]
Any update on this? same problem here.

**Comment by alexruskovski** [comment]
Its happening to me the same. Strange think here is that its working find on Api 24 and 25. The problem starts with api 23.  As a error I get:
java.net.UnknownHostException: "host83-33-237-212.serverdedicati.aruba.it"

I dont know from where this auba.it site even appear here... If any one figure it out please post the solution. 
v:1.4.9

**Comment by MatteoMilesi** [comment]
Some users of my app have the same issue (their devices are 100% Samsung right now, but I can't tell if it's related). I tried to downgrade to 1.4.8 and 1.4.7 with no luck.

**Comment by ExtremeKaos** [comment]
Same here, it works in api 24-25 or greatter, with 23 always 
"java.io.IOException: UnknownHostException exception: Unable to resolve host .."

**Comment by msgopalkrish** [comment]
Its seems problem in internet service provider.try with some other broadband/network.

**Comment by smarek** [comment]
For starters, use 1.4.8 or migrate to 1.5.0 when it becomes generally available / stable.
