### ISSUE TITLE
org.apache.http.client.HttpResponseException: Forbidden

### ISSUE THREAD

**Issue by lphgithub** [android-async-http/android-async-http#1238]
.sxzq W/System.err: org.apache.http.client.HttpResponseException: Forbidden
03-05 14:31:29.090 6933-6933/com.hundsun.stockwinner.sxzq W/System.err:     at com.loopj.android.http.AsyncHttpResponseHandler.sendResponseMessage(AsyncHttpResponseHandler.java:440)
03-05 14:31:29.090 6933-6933/com.hundsun.stockwinner.sxzq W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:78)
03-05 14:31:29.090 6933-6933/com.hundsun.stockwinner.sxzq W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:91)
03-05 14:31:29.090 6933-6933/com.hundsun.stockwinner.sxzq W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:54)
03-05 14:31:29.090 6933-6933/com.hundsun.stockwinner.sxzq W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
03-05 14:31:29.090 6933-6933/com.hundsun.stockwinner.sxzq W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
03-05 14:31:29.090 6933-6933/com.hundsun.stockwinner.sxzq W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
03-05 14:31:29.090 6933-6933/com.hundsun.stockwinner.sxzq W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)

**Comment by lphgithub** [comment]
before android  4.4,someone meet this question

**Comment by amervelic** [comment]
https://github.com/amitshekhariitbhu/Fast-Android-Networking
