### ISSUE TITLE
Basic authorization not working for GET request

### ISSUE THREAD

**Issue by tomkoptel** [android-async-http/android-async-http#124]
I have this snippet, still server returns `Basic authorization required`. I`ve checked the server work by doing the same in ruby code and it works. So the problem in my java code.

I guess that I have something wrong in java bellow, maybe some additional setup required.

``` java
String uri = 'my.domain.com/' + 'login';

AsyncHttpClient client = new AsyncHttpClient();
client.setBasicAuth("name", "password");

client.get(uri, new JsonHttpResponseHandler() { ... });
```

**Comment by empitechathu** [comment]
This is not working either :( :(
