### ISSUE TITLE
consuming REST APIs

### ISSUE THREAD

**Issue by ktcore** [android-async-http/android-async-http#1240]
Hello,

I am getting 400:bad request every time I POST. I am using it to get the access token from LinkedIn (oauth 2) by posting data. It works on POSTMAN but why its not working in the app. I am using ver 1.4.9 Thanks!!

AsyncHttpClient mClient = new AsyncHttpClient();
// send a post request to get the access token
RequestParams parameters = new RequestParams();

parameters.put("client_id",mLinkedInKey);
parameters.put("client_secret",mLinkedInSecret);
parameters.put("grant_type",grantType);
parameters.put("code",code);
parameters.put("redirect_uri",mRedirectURI);

//Set the headers
mClient.addHeader("Content-Type","x-www-form-urlencoded");

mClient.post(mAccessTokenEndPoint, parameters, new JsonHttpResponseHandler() {

//
@Override
public void onSuccess(int statusCode, Header[] headers, JSONObject responseBody) {
}

@Override
public void onFailure(int statusCode, Header[] headers, Throwable error, JSONObject errorBody) {
}
}

**Comment by smarek** [comment]
Such issues, unless you've got any hint it's issue of library, should be discussed on stackoverflow.com
