### ISSUE TITLE
Read time out. If the application goes into idle mode and then brought to foreground

### ISSUE THREAD

**Issue by prakashraman** [android-async-http/android-async-http#1241]
I have been noticing that some of the calls are just "timing out" once in a while. Although, I noticed that it "everytime" does timeout after the application come from the idle mode.

What could be the issue ?

02-13 16:33:07.589 20454-7737/apps1985.co.in.scoopwhoop W/System.err: java.net.SocketTimeoutException: Read timed out
02-13 16:33:07.595 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
02-13 16:33:07.595 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
02-13 16:33:07.595 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
02-13 16:33:07.595 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
02-13 16:33:07.595 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:223)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-13 16:33:07.596 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at java.lang.Thread.run(Thread.java:818)
02-13 16:33:07.597 20454-7737/apps1985.co.in.scoopwhoop W/System.err: java.net.SocketTimeoutException: Read timed out
02-13 16:33:07.597 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
02-13 16:33:07.597 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
02-13 16:33:07.597 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
02-13 16:33:07.597 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
02-13 16:33:07.597 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
02-13 16:33:07.597 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
02-13 16:33:07.597 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
02-13 16:33:07.597 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
02-13 16:33:07.597 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
02-13 16:33:07.597 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
02-13 16:33:07.599 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:223)
02-13 16:33:07.599 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
02-13 16:33:07.599 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
02-13 16:33:07.599 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
02-13 16:33:07.599 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
02-13 16:33:07.599 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
02-13 16:33:07.599 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
02-13 16:33:07.599 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
02-13 16:33:07.599 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
02-13 16:33:07.599 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
02-13 16:33:07.600 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-13 16:33:07.600 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-13 16:33:07.600 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-13 16:33:07.600 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-13 16:33:07.600 20454-7737/apps1985.co.in.scoopwhoop W/System.err:     at java.lang.Thread.run(Thread.java:818)
02-13 16:33:07.627 20454-20454/apps1985.co.in.scoopwhoop I/SW: [[ERROR]]: HTTP Failed, passing on to the failure (json) block: code: 0
02-13 16:33:07.627 20454-20454/apps1985.co.in.scoopwhoop I/SW: [[ERROR]]: Read timed out

**Comment by smarek** [comment]
Best coding practices should be discussed on stackoverflow.com
Issues in this project are meant to track bugs and feature requests, not general programming questions.
