### ISSUE TITLE
Unsafe implementation of Trustmanager

### ISSUE THREAD

**Issue by dpreussler** [android-async-http/android-async-http#1243]
reopened version of 
https://github.com/loopj/android-async-http/issues/1107

This is not a false alarm, this library contains an unsafe Trustmanager 
https://github.com/loopj/android-async-http/blob/f53deef7ad5b02b42b59dab92f66dec4fde8e1f6/library/src/main/java/com/loopj/android/http/MySSLSocketFactory.java

The issue this file is addressing was fixed in ICS
https://code.google.com/p/android/issues/detail?id=13117#c14

So it should be removed else apps using android-async-http will continue to receive letter of removal warnings from playstore.

**Comment by smarek** [comment]
Thanks for your report, this is solved in 1.5.0
