### ISSUE TITLE
Cant connect with "https" server

### ISSUE THREAD

**Issue by ZincFux** [android-async-http/android-async-http#1249]
Hello i cant con with my https server, what should i do ? I follow ur tutorial well.

**Comment by vishalkaushal-mprog** [comment]
facing same problem in kitkat. 
U got any solution ?

**Comment by deepankarb** [comment]
Can you post your code & stacktrace?

**Comment by smarek** [comment]
Thank you for the report, SSL/TLS related issue will be tracked in #1029. Closing this as duplicate
