### ISSUE TITLE
How to POST XML/JSON???

### ISSUE THREAD

**Issue by mustafa01ali** [android-async-http/android-async-http#125]
I've run into a problem with POSTing data. I have to post data to the API in the following format: -

```
\<request\>
  \<notes\>Test api support\</notes\>
  \<hours\>3\</hours\>
  \<project_id type="integer"\>3\</project_id\>
\</request\>
```

As per the documentation, I tried doing it using RequestParams, but it is failing. Is this any other way to do it? I can POST equivalent JSON too. Any ideas?

**Comment by shabbir-dhangot** [comment]
But What if I want to pass xml in body. @voidberg can you post some snippet regarding xml
