### ISSUE TITLE
20 second delay request,Reply me as soon as possible.Thanks.

### ISSUE THREAD

**Issue by LucianWang** [android-async-http/android-async-http#1250]
Why do I use SyncHttpClient for post requests. Probability of delay 20 before sending to the server?Please。
These two ports are used in the project：
public static String HOST ="192.168.22.16:19003";   public static String HOST2 ="192.168.22.16:19006";
This is initialization：
public SyncHttpClient asyncHttpClient = new SyncHttpClient();
    public Api(Context context) {
        this.context = context;
        this.mConnectTimeout = 5000;
        // this.mReadTimeout = 30000;
        asyncHttpClient.setTimeout(this.mConnectTimeout);
        asyncHttpClient.setEnableRedirects(true);
        asyncHttpClient.setURLEncodingEnabled(true);
        asyncHttpClient.setSSLSocketFactory(SSLCustomSocketFactory.getSocketFactory(context));
    }
Thank you!

**Comment by smarek** [comment]
Issues in this project are meant to track bugs and feature requests, not general programming questions.

**Comment by caiquesantosteixeira** [comment]
I really have a problem
