### ISSUE TITLE
call Asynchttp from intentService 

### ISSUE THREAD

**Issue by hidayatasep43** [android-async-http/android-async-http#1251]
i call Asynchttp from intentService and i get error 
Handler (com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler) {2590ad58} sending message to a Handler on a dead thread

**Comment by deepankarb** [comment]
Can you post your code and stacktrace? Also did you try to google with that message?

**Comment by smarek** [comment]
Issues in this project are meant to track bugs and feature requests, not general programming questions.
