### ISSUE TITLE
Is it possible to use this library to upload a video file to a server?

### ISSUE THREAD

**Issue by power7714** [android-async-http/android-async-http#1252]
I have seen older tuts for uploading a video to server using apache's http library but how would I do that with this library? I know it has to be a multipart request but I've seen people declaring FileBody(File). Is that mime type possible with this loopj library? Thank you. #

**Comment by MrSilverstone** [comment]
I guess that you found how to do it since, but I'm leaving it for others :

```
final AsyncHttpClient client = new AsyncHttpClient();
File file = new File(mVideoPath);

RequestParams params = new RequestParams();
params.put("file", file);

client.post(getContext(), mUploadUrl, params, new AsyncHttpResponseHandler() { ... });
```

**Comment by dionisi** [comment]
You can upload video file, but if it is big, you'll get OOM exception. 

I highly suggest to migrate to another library if possible, because according to this project is abandoned.
No changes since 2 years and too many serious issues.

**Comment by smarek** [comment]
Such issues, unless you've got any hint it's issue of library, should be discussed on stackoverflow.com
