### ISSUE TITLE
How to redo a request but change request data between requests?

### ISSUE THREAD

**Issue by AubreyKilian** [android-async-http/android-async-http#1253]
Hi guys,

I'm wondering if it's possible to retry a request from within the onFailure() method of the responsehandler?

For example, I have a request that does a POST to a server, and included in the POST DATA I have "userid=1", but the server responds with an HTTP 409 error (or other 4xx error), with an error message of "UserID already exists", so I want to change the POST DATA to have "userid=2" instead, and then do the request again.

I guess the bigger question is, should this really be dealt with inside the onFailure() method?  Or outside?  I basically want to keep redoing the POST until a valid userid is found.  Or, rather, the question should be: How would I go about redoing a request, but change the POST DATA between requests, if onFailure() is called?

Thanks
-Aubrey

**Comment by AubreyKilian** [comment]
Using 1.4.9 on Android 6.x

**Comment by smarek** [comment]
No, in onFailure the request is already ended, you have to make the .post() call again
