### ISSUE TITLE
about "No valid URI scheme was provided"

### ISSUE THREAD

**Issue by Ren-yibo** [android-async-http/android-async-http#1254]
I use 1.4.8 version and use "post" method,but i get "java.net.MalformedURLException: No valid URI scheme was provided" all the time,please help ,thank you.

**Comment by ShiverZm** [comment]
so do i, but i don't know how to solve it, i  have to add frame "okgo" to use

**Comment by ShiverZm** [comment]
i knew how to solve it, add " httpClient.setURLEncodingEnabled(false);"
