### ISSUE TITLE
JSON get response issue

### ISSUE THREAD

**Issue by makR00** [android-async-http/android-async-http#1255]
I want to simulate a JSON response for a get method which returns a list. Using loopj on the client and jersey on the server. From the client I am calling a get method. Here is code - Calling method in client:

`
```
private void getItems(){
        RequestParams rp = new RequestParams();
        HttpUtils.get("ItemService/items", rp,
                    new JsonHttpResponseHandler() {
                        @Override
                        public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
                            // If the response is JSONObject instead of expected JSONArray
                            try {
                                Log.d("ItemDetailActivity", "onSuccess 1 ---------------- this is response : " + response);
                                //JSONObject serverResp = new JSONObject(response.toString());
                            } catch (Exception e) {
                                // TODO Auto-generated catch block
                                e.printStackTrace();
                            }
                        }

                        @Override
                        public void onSuccess(int statusCode, Header[] headers, JSONArray timeline) {
                            // Pull out the first event on the public timeline
                            try {
                                Log.d("ItemDetailActivity", "onSuccess 2 ---------------- this is response : " + timeline);
                            } catch (Exception e) {
                                // TODO Auto-generated catch block
                                e.printStackTrace();
                            }
                        }

                        @Override
                        public void onFailure(int statusCode, Header[] headers, String responseString, Throwable t) {
                            // Pull out the first event on the public timeline
                            Log.e("ItemDetailActivity", "---------------- this is failure response : " + statusCode + " || " + responseString + " || " +t.fillInStackTrace());
                        }
                    }
                );
    }
```
`

The code in HttpUtils

`
```
public class HttpUtils {

    //Since its running in Emulator - replace localhost or 127.0.0.1 with 10.0.2.2
    private static final String BASE_URL = "http://10.0.2.2:8080/ApacheDBUtil/rest/";

    private static AsyncHttpClient client = new AsyncHttpClient();

    public static void get(String url, RequestParams params, AsyncHttpResponseHandler responseHandler) {
        String s = getAbsoluteUrl(url);
        client.addHeader("Accept", "application/json");
        client.addHeader("Content-type", "application/json");
        client.get(s, params, responseHandler);
    }

    private static String getAbsoluteUrl(String relativeUrl) {
        return BASE_URL + relativeUrl;
    }
}
```
`

The server code

`
```
@Path("/ItemService")
public class ItemService {
    @GET
    @Path("/items")
    @Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
    public List<Item> getItems() throws Exception {
        List<Item> items = null;
        try {
            DBInteractionManager dbconn = new DBInteractionManager();
            items = dbconn.getAllItems(1);

        } catch (Exception e) {
            e.printStackTrace();
        }
        return items;
    }
}
```
`

The error I am getting is :

`
ItemDetailActivity: ---------------- this is failure response : 500 || <!DOCTYPE html><html><head><title>Apache Tomcat/8.5.11 - Error report</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style> </head><body><h1>HTTP Status 500 - Internal Server Error</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>Internal Server Error</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><hr class="line"><h3>Apache Tomcat/8.5.11</h3></body></html> || cz.msebera.android.httpclient.client.HttpResponseException:
`

if I remove the following lines in HttpUtils -
`
client.addHeader("Accept", "application/json");
client.addHeader("Content-type", "application/json");
`

The response (error) is 
`
ItemDetailActivity: ---------------- this is failure response : 200 || <?xml version="1.0" encoding="UTF-8" standalone="yes"?><items><item><itemGroupid>0</itemGroupid><itemid>13</itemid><name>Remote Car</name><notes>Works forward only</notes><status>Available</status></item></items> || org.json.JSONException: Response cannot be parsed as JSON data
`

What am I doing wrong to get a JSON get response w/o error?

**Comment by smarek** [comment]
Issues in this project are meant to track bugs and feature requests, not general programming questions.
Closing as invalid
