### ISSUE TITLE
Acces https 

### ISSUE THREAD

**Issue by hidayatasep43** [android-async-http/android-async-http#1257]
Hello .. 
i can connect to https 
i use this code 

AsyncHttpClient client;
if(isAsync()) {
    client = new AsyncHttpClient(true, 80, 443);
} else {
     client = new SyncHttpClient();
}
client.setTimeout(10 * 1000);
client.setMaxRetriesAndTimeout(3, 10 * 1000);
if (getMethod() == Method.POST)
       client.post(url, params, getAsyncResponseHandler());
else
      client.get(url, params, getAsyncResponseHandler());

but the response from server is 

```html
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>cloudflare-nginx</center>
 </body>
 </html>
```

**Comment by smarek** [comment]
This is not issue of the library.
