### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by Bekakk** [android-async-http/android-async-http#1265]
Hello
I'm using your repository and i have one problem. I guess it supports only TLSv1.0. Any help?

**Comment by nicowxdvd** [comment]
anyone?

**Comment by pdrogfer** [comment]
I am having a similar problem

**Comment by nicowxdvd** [comment]
Try this

private static AsyncHttpClient client   = new AsyncHttpClient(true, 80, 443);

work form me

**Comment by pdrogfer** [comment]
Thanks, will try

**Comment by saigowthamtk** [comment]
Hi @nicowxdvd its not working under 6 version, do you have any idea to slove this?

**Comment by nicowxdvd** [comment]
Nup, but you need to try set HTTPS config in the object

**Comment by smarek** [comment]
Thank you for the report, SSL/TLS related issue will be tracked in #1029. Closing this as duplicate
