### ISSUE TITLE
Pen Test - Insecure Random Number Generator – (Android)

### ISSUE THREAD

**Issue by sumvis** [android-async-http/android-async-http#1267]
Hi,

I am using this android-async-http lib version 1.4.4 in my android application.
There is a class SimpleMultipartEntity which uses insecure random number and this file can be victim of random number generator attack as it uses Java Random class to generate random number. We should use SecureRandom class instead of this. 
here is the link of the tool, we used for code scan.
https://github.com/MobSF/Mobile-Security-Framework-MobSF

I have also checked the latest version of this lib and that also uses the same Java Random class.

Could you please look into this and make this lib more secure?

Thanks and regards,
Sumit Kumar

**Comment by smarek** [comment]
Well, since the Random was used only to generate boundary identifier, and not doing encryption/signature/crypto, it is no issue. Thank you for concerns tho'
