### ISSUE TITLE
File uploading issue 

### ISSUE THREAD

**Issue by SagarRaiyani** [android-async-http/android-async-http#1269]
Hello,

I have some issue in file uploading in loopj library 
I have use same as code in your example but getting error like this "W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection" 

and my code is 

           RequestParams params = new RequestParams();
            final String contentType = RequestParams.APPLICATION_OCTET_STREAM;
            File myFile = new File(imagepath);
            try {
                params.put(Const.PARAMS.IMAGE, myFile,contentType,myFile.getName());
                params.setHttpEntityIsRepeatable(true);
                params.setUseJsonStreamer(false);
            } catch (FileNotFoundException e) {
                e.printStackTrace();   
            }

Please give me solution for this.

**Comment by smarek** [comment]
This is not issue of the library.
