### ISSUE TITLE
Android: long first request (wifi without internet)

### ISSUE THREAD

**Issue by hamipos** [android-async-http/android-async-http#1272]
I am using the AsyncHttpClient from loopj.com/android-async-http. The first response in local WiFi (without Internet) is always going to take longer (about 15 sec) than a local WiFi with Internet. I am using two different instance of this class and this problem occurs twice. Example URL:
`http://192.168.0.18/test/rest/v1`
After first executed request everything works fine, and the time response is <1 sec.

**Comment by smarek** [comment]
This is not issue of the library. Seems like routing / resolving issue on device side, and without further LogCat output, I'm unable to provide any clarification. Feel free to provide more info and reopen this issue
