### ISSUE TITLE
ConcurrentSkipList file is missing

### ISSUE THREAD

**Issue by vikasrairajput** [android-async-http/android-async-http#1274]

**Comment by ghzjtian** [comment]
I meet this too,somebody can help?

**Comment by kevinlee0625** [comment]
I meet this problem too，and I get headache

**Comment by kevinlee0625** [comment]
I resolve the problem by changing the ConcurrentSkipList to ConcurrentHashMap, and you must delete the imported item(import java.util.concurrent.ConcurrentSkipList ).

**Comment by smarek** [comment]
ConcurrentSkipList has been replaced due to dropped support in android base-sdk
