### ISSUE TITLE
URLEncoding with %2F leads to request issues

### ISSUE THREAD

**Issue by Sese-Schneider** [android-async-http/android-async-http#1279]
If you request an URL e.g. `http://example.com/thumbnails/testfolder%2Fimage.png` AsyncHttpClient converts this to: `http://example.com/thumbnails/testfolder/image.png` and requests this url instead (which it defently shouldn't)!

> `%2F` is the URLEncoded char `/`

Quick workaround is: `asyncHttpClient.setURLEncodingEnabled(false)` (use with caution)

**Comment by smarek** [comment]
You pointed out correct way to solve your problem, however automatically encoding/decoding urls is something that works for everyone else, and not converting %2F to slash char seems a tad weird to me. This won't be addressed on library side.
