### ISSUE TITLE
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'. > com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by xristos4hax** [android-async-http/android-async-http#1280]
i have this error.. i cant run my app. 
![androidstudioerror](https://user-images.githubusercontent.com/31169578/34738242-17f02a22-f581-11e7-9cd3-f731f6b9052a.png)

**Comment by Wesely** [comment]
Have you compile (implementation) some of the other HTTP package in your .gradle dependencies?
In my case, I removed "org.apache.http.client:4.1.2" 
It seems they will conflict.

**Comment by smarek** [comment]
This is dependency clash / dev environment problem, not something I could help you with.
