### ISSUE TITLE
how to post int value in RequestParams

### ISSUE THREAD

**Issue by drd1988on** [android-async-http/android-async-http#1281]
Hi
I wants to pass int value as parameters in RequestParams.put ("val",1);
But I could see that in the RequestParams class ,it have a method which accepts int value,but inside that method it converts the int value to string.
Code snippet from RequestParam Class
===================================== 
/**
     * Adds a int value to the request.
     *
     * @param key   the key name for the new param.
     * @param value the value int for the new param.
     */
    public void put(String key, int value) {
        if (key != null) {
            urlParams.put(key, String.valueOf(value));
        }
    }
========================================
So at by server side it is expecting an int value not string.So the response is empty.
Is there any method to overcome this?

Regards
Divya

**Comment by smarek** [comment]
This will be solved using new RequestParams. With library version 1.4.x it is currently impossible to send int as int, sorry about that
