### ISSUE TITLE
Didn't work in android 6.0 and lower versions when i use  com.loopj.android:android-async-http:1.4.9 library 

### ISSUE THREAD

**Issue by VenkataKrishna1944** [android-async-http/android-async-http#1283]
In my application for the login and registration pages, I used web services in that I used async-HTTP client but when I run that application on android 7.0 it's working but not in lower android versions. why?

**Comment by vl25** [comment]
on my api level 15 (Andorid 4) work perfect

**Comment by smarek** [comment]
Such issues, unless you've got any hint it's issue of library, should be discussed on stackoverflow.com
