### ISSUE TITLE
Constantly receiving response code 400??

### ISSUE THREAD

**Issue by ARAlmac** [android-async-http/android-async-http#1284]
Hi Everyone,
I am a beginner and have been struggling with this problem for a week now. I have an android mobile application and want to send variables to my oracle database through my RESTapi. I have tried multiple libraries and this seems to be the one I understand most. However, no matter what I try I am receiving response code 400 and I am literally at a brick wall.  I have used postman and my requests are working correctly with the same headers and I am using JSON raw body. I have tried to send the data using JSON but it says it expects Request params. 
Here is my code: 

` private void onemoretime() {
        AsyncHttpClient client = new AsyncHttpClient();

        client.addHeader("Content-Type", "application/json");
        client.addHeader("securityToken", "Good Token");

        RequestParams params = new RequestParams();
        params.put("machineType", machineType);
        params.put("workOrderNumber", workOrderNumber);
        params.put("employeeName", employee);
        params.put("activity", activity);
        params.put("durationHours", String.valueOf(durationHours));
        params.put("durationMins", String.valueOf(durationMins));
        params.put("downtimeHours", String.valueOf(downTimeHours));
        params.put("downtimeMins", String.valueOf(downTimeMins));
        params.put("details", details);
        params.put("createdTimestamp", currentDateandTime);

        client.post("http://172.17.124.156:8080/engAppApi/webservices/engineerTable/", params, new AsyncHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                Toast.makeText(getApplicationContext(), statusCode,
                        Toast.LENGTH_LONG).show();
            }

            @Override
            public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                Toast.makeText(MainActivity.this, "Error Occurred" + error.getCause(), Toast.LENGTH_SHORT).show();

            }

        });

    }`

Someone please help :(

**Comment by harleyknd1** [comment]
are you sure the variables you're adding exist?
are you also sure you need to add headers?
400 is a Bad Request, so I'm assuming either your parameters are null, or the headers you're setting is incorrect.

Try doing a post request with a statically defined variable and see if it works 
(also set breakpoints to verify all the variables are set properly)

**Comment by smarek** [comment]
This is not issue of the library.
