### ISSUE TITLE
SSLHandshakeException - handshake failed (android 6)

### ISSUE THREAD

**Issue by elirantutia** [android-async-http/android-async-http#1287]
There is an issue in Android 6 (I guess in 5 and less as well) when trying to send https request. In Android 7 it works great.

Exception:
`javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x7f60267c9c80: Failure in SSL library, usually a protocol error
error:100c5438:SSL routines:ssl3_read_bytes:TLSV1_ALERT_INTERNAL_ERROR (external/boringssl/src/ssl/s3_pkt.c:972 0x7f6038c9a540:0x00000001)`

**Comment by zeero0** [comment]
I was facing this issue and tried almost every solution.
The solution which worked for me is to use this version of library:
    compile 'com.loopj.android:android-async-http:1.4.8'

and for Headers[] I used 

    android {
        useLibrary 'org.apache.http.legacy'
    }

**Comment by stevemann2705** [comment]
@zeero0 It worked for me. Although org.apache.http.Header is deprecated, so the solution works well in Android 6 but for versions above(I tested on Android 9), I also had to add 
``<uses-library android:name="org.apache.http.legacy" android:required="false" />``
in <application> tag of Manifest file. 

See: https://stackoverflow.com/a/50779232

**Comment by behroohj** [comment]
I found a solution, you can use version 1.4.9 but you should define all imports one by one then the problem will solve.
replace
`import com.loopj.android.http.*;`
with
`import cz.msebera.android.httpclient.Header;
import com.loopj.android.http.AsyncHttpClient;
import com.loopj.android.http.AsyncHttpResponseHandler;
import com.loopj.android.http.RequestParams;`
