### ISSUE TITLE
Android Studio 3.1: Failed to resolve: android-async-http

### ISSUE THREAD

**Issue by Jacky-Xu** [android-async-http/android-async-http#1291]
![qq 20180328184515](https://user-images.githubusercontent.com/10206252/38024670-4491af1e-32b8-11e8-9596-d7a555950545.png)

**Comment by sgiurgiu** [comment]
Got the same issue here. Apparently gradle 4.4 cannot find the cz.msebera.android.httpclient jars. It can find the com.loopj.android.http jars just fine. My workaround was to add this to build.gradle:

implementation "cz.msebera.android:httpclient:4.4.1.2"

**Comment by Jacky-Xu** [comment]
@sgiurgiu  I tried to use your method, but the problem is still unresolved.

**Comment by Jacky-Xu** [comment]
@sgiurgiu version 1.4.8,you try it，it's not Failed to resolve.

**Comment by Jacky-Xu** [comment]
@sgiurgiu   in your app gradle : useLibrary 'org.apache.http.legacy'

**Comment by harleyknd1** [comment]
build.gradle (app)
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 26

    defaultConfig {
        applicationId "nl.alternate.mobirails"
        minSdkVersion 22
        targetSdkVersion 26
        versionCode 23
        versionName "23.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    // ... other dependencies
    api files('libs/android-async-http-1.4.9.jar')
    api files('libs/jcifs-1.3.19.jar')
    api 'com.squareup.okhttp3:okhttp:3.4.1'
    api 'cz.msebera.android:httpclient:4.3.6'
}`

the gradle file I use, might help

also remember to put the zip in project_dir->app->libs

**Comment by ParryPatel021** [comment]
> build.gradle (app)
> 
> ```
> apply plugin: 'com.android.application'
> 
> android {
>     compileSdkVersion 26`
> 
> 
>     defaultConfig {
>         applicationId "com.company.program"
>         minSdkVersion 22
>         targetSdkVersion 26
>         versionCode 23
>         versionName "23.0"
>     }
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
> }
> 
> dependencies {
>     api fileTree(include: ['*.jar'], dir: 'libs')
>     // ... other dependencies
>     api files('libs/android-async-http-1.4.9.jar')
>     api files('libs/jcifs-1.3.19.jar')
>     api 'com.squareup.okhttp3:okhttp:3.4.1'
>     api 'cz.msebera.android:httpclient:4.3.6'
> }
> ```
> the gradle file I use, might help
> 
> also remember to put the jar in project_dir->app->libs

There should be an **implementation** keyword instead of an **api**.
Because at the end of 2018, api & compile keywords are going to be removed.

**Comment by smarek** [comment]
Relevant answers has been provided, thank you all.
Closing this ticket, as it is no issue of library, only problem on developer-side
