### ISSUE TITLE
Getting HTTPResponseException : ModSecurity Action

### ISSUE THREAD

**Issue by sidpal7747** [android-async-http/android-async-http#1295]
I am getting this exception after hitting API which is working fine in POSTMAN.
What does it mean?

**Comment by harleyknd1** [comment]
> ModSecurity Action

Usually means your mod security settings aren't allowing you to do the thing you're trying to do.
For example, a Webserver may have a security setting restricting users from directly accessing the api without authentication.

ModSecurity settings can also blacklist ip addresses and do other things.
Set a breakpoints in your onFailure and check what the Throwable says for additional details

**Comment by smarek** [comment]
This is not a bug related to the library
