### ISSUE TITLE
How to send boolean on RequestParams.put()?

### ISSUE THREAD

**Issue by denniskeithgaso** [android-async-http/android-async-http#1299]
It seems that the boolean value I passed on the `put()` method doesn't work.
The server cannot interpret the boolean value.
How do I send a boolean value to the server?

`
params.put("before_timestamp", false);
`

**Comment by harleyknd1** [comment]
> params.put("before_timestamp", 0);

on your server side 

> if (before_timestamp == 0) {}

When using params.put, you're putting parameters in your post (or get) request, essentially what you're doing is

> http://example.com/somePage?before_timestamp=false

This is intended and works the same way as php, and other web languages, on the other end you can either keep it this way, and use the parameter as a string (e.g before_timestamp == "false") or you can use integers 0 and 1 instead.

**Comment by smarek** [comment]
This is not issue of the library
