### ISSUE TITLE
Can't upload an image as a file. On failed method called every time

### ISSUE THREAD

**Issue by imranali07** [android-async-http/android-async-http#1304]
package com.appxone.imageupload;

import android.app.ProgressDialog;
import android.content.Intent;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.Uri;
import android.os.Environment;
import android.provider.MediaStore;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.loopj.android.http.AsyncHttpClient;
import com.loopj.android.http.AsyncHttpResponseHandler;
import com.loopj.android.http.FileAsyncHttpResponseHandler;
import com.loopj.android.http.JsonHttpResponseHandler;
import com.loopj.android.http.RequestParams;
import com.squareup.picasso.Picasso;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;

import cz.msebera.android.httpclient.Header;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.RequestBody;
import okio.BufferedSink;

public class MainActivity extends AppCompatActivity implements View.OnClickListener {

    public static final int REQUEST_CODE = 100;
    public static final String TAG = MainActivity.class.getSimpleName();
    public static final String IMAGE_URL = "http://sellmyoutfit.com/projects/sell_outfit/edit_profile.php";
    ImageView profileImage;
    TextView imageUri;
    Button pickImageFromGallery, uploadImage;
    AsyncHttpClient asyncHttpClient;
    //File file;
    String filePath;
    ProgressDialog pDialog;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        profileImage = findViewById(R.id.profile_image);
        imageUri = findViewById(R.id.image_uri);
        pickImageFromGallery = findViewById(R.id.pick_image);
        uploadImage = findViewById(R.id.upload_image);
        asyncHttpClient = new AsyncHttpClient();
        pickImageFromGallery.setOnClickListener(this);
        uploadImage.setOnClickListener(this);
        pDialog = new ProgressDialog(this);
        pDialog.setMessage("Uploading Image");
        pDialog.setCancelable(true);

    }

    @Override
    public void onClick(View view) {
        switch (view.getId()){
            case R.id.pick_image:
                pickImageFromGallery();
//                imageUri.setVisibility(View.VISIBLE);
//                imageUri.setText("Image Uri"+ path);
                break;

            case R.id.upload_image:
                uploadImage(filePath);
                break;
        }
    }
    private void pickImageFromGallery(){
        Intent galleryIntent = new Intent(Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
        startActivityForResult(galleryIntent, REQUEST_CODE);

    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if(requestCode == REQUEST_CODE && resultCode == RESULT_OK && data != null){
            Uri imageUri = data.getData();
            profileImage.setImageURI(imageUri);
            filePath = getPath(imageUri).trim();
//            path = getPath(imageUri);
//            path = file.getPath();
            Log.d(TAG, "onActivityResult: " + filePath);

        }
    }

    private String getPath(Uri imageUri) {
        String[] projection = {MediaStore.Images.Media.DATA};
        Cursor cursor = getContentResolver().query(imageUri, projection, null, null, null);
        cursor.moveToFirst();
        int columnIndex = cursor.getColumnIndex(projection[0]);
        String path = cursor.getString(columnIndex);
        cursor.close();
//        profileImage.setImageBitmap(BitmapFactory.decodeFile(filePath));
        return path;
    }

    private void uploadImage(String path) {
        pDialog.show();
        File file = new File(filePath);
        Log.d(TAG, "uploadImage: " + file);
        RequestParams params = new RequestParams();
        try {
            params.put("fileToUpload", file);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        params.put("user_id", "39");
        params.put("session_id", "2c02e42b991eddd63e5be030016a15fc");
        Log.d(TAG, "uploadImage: " + params);
        asyncHttpClient.post(MainActivity.this, IMAGE_URL, params, new AsyncHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                String response = new String(responseBody);
                Log.d(TAG, "onSuccess: " + response);
                try {
                    JSONObject jsonObject = new JSONObject(response);
                    Log.d(TAG, "onSuccess: " + jsonObject);
                    String imagePath = jsonObject.getString("image");
                    String status = jsonObject.getString("status");
                    String message = jsonObject.getString("message");
                    String time = jsonObject.getString("time_stamp");
                    String session_status = jsonObject.getString("session_status");
                    if (status.equals("true") && session_status.equals("true")) {
                        Picasso.get().load(imagePath).into(profileImage);
                    } else
                        Toast.makeText(MainActivity.this, "Something went wrong", Toast.LENGTH_SHORT).show();
                    pDialog.dismiss();
                } catch (JSONException e) {
                    Log.d(TAG, "onSuccess: " + e.getMessage());
                    pDialog.dismiss();
                }
            }

            @Override
            public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                Toast.makeText(MainActivity.this, "Image Uploading Failed", Toast.LENGTH_SHORT).show();
                Log.d(TAG, "onFailure: " + error.getMessage());
                pDialog.dismiss();

            }
        });
    }
}

**Comment by smarek** [comment]
If you provide more info, specifically stacktrace of error you've got in onFailure callback, feel free to reopen this issue
