### ISSUE TITLE
Provide support for the latest API level

### ISSUE THREAD

**Issue by ebghrimtech** [android-async-http/android-async-http#1305]
Hello,
We are currently using your library in one of our application. Actually we need a favour from your side. According to the Google Play Policy, all apps have to provide support for at least API level 26 which is not satisfied in your case. We are targeting API level 28. So can you please provide us support for API level 28 in your current repository?

**Comment by smarek** [comment]
1.5.0-SNAPSHOT currently provides that, however the release will come in 1-2 months, sincerely i'm currently (again) the only maintainer of this project
