### ISSUE TITLE
HTTPS : Unknown error during handshake

### ISSUE THREAD

**Issue by ashishtikarye** [android-async-http/android-async-http#1306]
javax.net.ssl.SSLException: SSL handshake aborted: ssl=0x61654530: I/O error during system call, Connection reset by peer

there is https URL issue when request on API and is it fix or not?

**Comment by riturajsuman** [comment]
https://stackoverflow.com/questions/30538640/javax-net-ssl-sslexception-read-error-ssl-0x9524b800-i-o-error-during-system

**Comment by ashishtikarye** [comment]
@riturajsuman Thanks for the link.
But it used **okhttp** and i am not used that. so this not work for me i need solution for **'com.loopj.android:android-async-http:1.4.9'** network library.

**Comment by smarek** [comment]
Thanks, this will be solved in #1029, where I'll concentrace issues about using new underlying HttpClient library and cross-support of SSL/TLS versions vs. Server supported versions
