### ISSUE TITLE
Insecure use of the https protocol can result in the interception of sensitive information and man-in-the-middle attacks.

### ISSUE THREAD

**Issue by yaok2012** [android-async-http/android-async-http#1307]
[ Problem Description ] 不安全的使用https协议会导致敏感信息被截获、中间人攻击。
[ Solve ] 1.不要使用自定义的HostnameVerifier和TrustManager，如果必须使用，请确定verify()方法中的验证策略正确；2.不要使用系统提供的AllowAllHostnameVerifier方法；

证书验证使用自定义函数，TrustManager被重写，可能存在安全风险。
com/loopj/android/http/MySSLSocketFactory.java	MySSLSocketFactory.getNewHttpClient(KeyStore) : DefaultHttpClient;
com/loopj/android/http/MySSLSocketFactory.java	MySSLSocketFactory.1.checkServerTrusted(X509Certificate[], String) : void

Hostname验证方法使用系统自带方法，该方法会允许所有主机。
com/loopj/android/http/MySSLSocketFactory.java	MySSLSocketFactory.getFixedSocketFactory() : SSLSocketFactory;

证书验证方法可能存在安全风险。
com/loopj/android/http/MySSLSocketFactory.java	MySSLSocketFactory.fixHttpsURLConnection() : void

**Comment by smarek** [comment]
Cheers, library by-default does not use insecure SSL protocols or verification methods, but it's up to developer, to choose such, and in these cases, we take no responsibility.

Thanks for the notification tho'
