### ISSUE TITLE
Android network profiler

### ISSUE THREAD

**Issue by deinega** [android-async-http/android-async-http#1308]
I am using Android Network Profiler, and I can't see htpp requests done using AsyncHttpClient... 
Is it how is it supposed to me ? Which tool I can use to monitor http requests in Android Studio?

Thank you !

**Comment by smarek** [comment]
Per documentation on https://developer.android.com/studio/profile/network-profiler
>Currently, the Network Profiler supports only the HttpURLConnection and OkHttp libraries for network connections.

>If your app uses another network connection library, you may not be able to view your network activity in the Network Profiler.

>If you have received this error message, but your app does use HttpURLConnection or OkHttp, please report a bug, or search the issue tracker to include your feedback in an existing report that's related to your issue. You can also use these resources to request support for additional libraries.
