### ISSUE TITLE
library not working after switching from proguard to R8

### ISSUE THREAD

**Issue by CHAKlBDEV** [android-async-http/android-async-http#1311]
Updating to Android Studio 3.4 caused the library to break. Found this on logcat
```
E/AsyncHttpRequest: Unhandled exception origin cause
$Proxy7 cannot be cast to a.b.e.e....
```
R8 is the default code shrinker now so I thought maybe that's what caused the problem, so I added these rules to proguard-rules.pro 
```
-keep class cz.msebera.android.httpclient.** { *; }
-keep class com.loopj.android.http.** { *; }
```
And it worked just fine. But the final apk is significantly larger in size.

**Comment by guchuanhang** [comment]
I 'm willing to have a try! However, my Android Studio 3.2 is fail to upgrade to  3.4. But I notice something like that 

> R8 is available with Android Studio 3.3 beta and works with Proguard rules. To try it, set the following in your project’s gradle.properties file:  android.enableR8=true
[](https://chinagdg.org/2018/11/r8-the-new-code-shrinker-from-google-is-available-in-android-studio-3-3-beta/)
So I think if you can do as inverse.set  android.enableR8=false

Good luck!

**Comment by ericbatemandev** [comment]
Adding rules to `proguard-rules.pro` worked for me as well. Thanks!

**Comment by smarek** [comment]
Cheers, i'll leave this open until documentation will be updated

**Comment by stevenflesch** [comment]
This affected my app with the same `E/AsyncHttpRequest: Unhandled exception origin cause` error mysterisouly appearing in my logs, and **ONLY** on my production builds.  Adding the `proguard-rules.pro` rules has allowed my app to behave again.  This is a breaking issue when using Android Studio 3.4!

Thanks for the help all!

**Comment by saeed-rz** [comment]
[Proguard Rules](https://github.com/android-async-http/android-async-http/wiki/proguard-rules)
