### ISSUE TITLE
This library has some issue... When HTTP calls are given with background thread response from server takes ages

### ISSUE THREAD

**Issue by tusharuit25** [android-async-http/android-async-http#1313]
As I described in issue title,This library does not work well. But same thing done with retrofit give result faster.

**Comment by smarek** [comment]
Well provide some debug info, if you want to get this library fixed.
Otherwise I'll close this issue as pointless

**Comment by tusharuit25** [comment]
Compare api responses with retrofit . You will find the issue.  It exist and I will not recommend  this library to anyone... I used this library for my product from 1.0.0 to 1.0.10 but one day my programmer shown me difference in API response and I lost trust though you can cross check.

**Comment by smarek** [comment]
Thanks, for such discussions use other means of communications, issues in the project exist to discuss existing issues and/or feature requests, this is neither

**Comment by tusharuit25** [comment]
Whenever I will find time will send you old version and new version api response video. This is not issue to be ignored people work on million dollar projects and their money is not for such a waste.

**Comment by smarek** [comment]
You're funny guy, if you work on million dollar projects and rely on free-provided in-free-time-developed library, and blame the library for your fault, then you are not very bright.

As a CTO you should know better. Don't bother sending video, if your developer wants, I'll be glad for technical suggestions or bug reports, but don't you try put the blame on me.

If you want work to be well done, you should pay-up, and if you're not willing to do that, then act humbly and hope for the best.

If you like different free-provided project more, well use it, and don't bother coming back

Best Regards

**Comment by tusharuit25** [comment]
It's not blame game from me at all and it's not fun either try to take inspiration from criticism. I made my point that it won't as expected. If you don't take responsibility for your free stuff even don't fight for it... Using free stuff is not crime either . I am alerting other people they should check before they move on with this networking library ; However i do not underestimate what you are serving for free effort counts.  You will definitely find support from other users. 
regards.
