### ISSUE TITLE
SAXParserFactory对象需设置参数防止外部实体注入

### ISSUE THREAD

**Issue by yaok2012** [android-async-http/android-async-http#1315]
问题文件
com/loopj/android/http/SaxAsyncHttpResponseHandler.java

特征信息
SaxAsyncHttpResponseHandler.getResponseData(HttpEntity) : byte[]

修复方案
factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true)；
或者需要设置这两个（少一个都不行）
factory.setFeature("http://xml.org/sax/features/external-general-entities", false)；
factory.setFeature("http://xml.org/sax/features/external-parameter-entities", false);

**Comment by smarek** [comment]
I can provide support only in English, closing due to language barier.
