### ISSUE TITLE
加密方式存在被破译的风险

### ISSUE THREAD

**Issue by yaok2012** [android-async-http/android-async-http#1316]
程序中使用了弱摘要算法，存在被破译的风险。风险等级：高。		
问题文件
cz/msebera/android/httpclient/impl/auth/NTLMEngineImpl.java
特征信息
NTLMEngineImpl.ntlm2SessionResponse(byte[], byte[], byte[]) : byte[]

问题文件
cz/msebera/android/httpclient/impl/auth/NTLMEngineImpl.java
特征信息
NTLMEngineImpl.HMACMD5.HMACMD5(byte[]) : void

程序中使用了弱加密算法，存在被破译的风险。风险等级：高。		
问题文件
com/baidu/android/bbalbs/common/a/a.java
com/baidu/android/bbalbs/common/a/a.java
com/baidu/android/pushservice/j/a.java
com/baidu/android/pushservice/j/a.java

特征信息
a.a(String, String, byte[]) : byte[]
a.b(String, String, byte[]) : byte[]
a.b(String, String, byte[]) : byte[]
a.a(String, String, byte[]) : byte[]

**Comment by smarek** [comment]
I can provide support only in English, closing due to language barier.
