### ISSUE TITLE
Problems with ° character JSON upload

### ISSUE THREAD

**Issue by paulfemiak** [android-async-http/android-async-http#1320]
One of the text fields inside of my JSON upload payload contains a ° character. This triggers 500 error response scenario.

**Comment by saeed-rz** [comment]
can you test your server with this code
`URLEncoder.encode("°", "utf-8");`
encode your param when you want fill it in AsyncHttpClient.

**Comment by paulfemiak** [comment]
Thank you @saeed-rz for replying, however I decided to move to another networking library. I'm going to close this issue now as I won't be able to follow up on additional testing.

**Comment by smarek** [comment]
@paulfemiak thank you for getting back to us.

fyi. I don't think that mentioned is issue of networking library, if the server does not return 4xx http code for invalid request/data/url scenario, 5xx is server/internal error, and clearly bad backend implementation.
