### ISSUE TITLE
PersistentCookieStore dont work, send post session is lost

### ISSUE THREAD

**Issue by langwan** [android-async-http/android-async-http#1327]
one post url is login 
second post is item list

but session is lost in the server.

What's my problem?

(debug mode is http, release mode is https)

`package com.langwan.safephotoandroid.utils;

import android.util.Log;

import com.langwan.safephotoandroid.MainActivity;
import com.langwan.safephotoandroid.activity.RegisterOneActivity;
import com.loopj.android.http.AsyncHttpClient;

import com.loopj.android.http.JsonHttpResponseHandler;
import com.loopj.android.http.PersistentCookieStore;
import com.loopj.android.http.RequestParams;
import cz.msebera.android.httpclient.Header;
import org.json.JSONObject;

import javax.net.ssl.SSLContext;

import cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory;

public class HttpManager {

    private static final HttpManager instance = new HttpManager();

    private AsyncHttpClient client = null;

    private HttpManager() {

    }

    public static HttpManager share() {
        return instance;
    }

    public void post(String uri, RequestParams params, final JsonHttpResponseHandler responseHandler) {

        if (client == null) {
            Log.d("api", "new client");
            client = new AsyncHttpClient();
           
            PersistentCookieStore cookie = new PersistentCookieStore(MainActivity.Companion.getStaticContent());
            client.setCookieStore(cookie);
            SSLSocketFactory sf = null;
            try {

                sf = new SSLSocketFactory(
                        SSLContext.getDefault(),
                        SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);

            }catch(Exception e) {
                e.printStackTrace();
            }

            client.setSSLSocketFactory(sf);
        }

        client.addHeader("accept-language", "zh");

        String url = Environment.getHttpApi() + uri;

        client.post(url, params, new JsonHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
                super.onSuccess(statusCode, headers, response);

                if (statusCode != 200) {
                    return;
                }

                responseHandler.onSuccess(statusCode, headers, response);
            }
        });

    }
}
`

**Comment by saeed-rz** [comment]
i think you should add cookie in header, check server code for cookie value name
test this code and let me know about result

> myCookieStore = new PersistentCookieStore(getApplicationContext());
            List<Cookie> cookies = myCookieStore.getCookies();
            String phpSession = "";
            if (cookies.isEmpty()) {
                Log.i("TAG", "None");
            } else {
                for (int i = 0; i < cookies.size(); i++) {
                        phpSession = cookies.get(i).getName()+"="+cookies.get(i).getValue()+";";
                }
                Log.i("session", phpSession);
            }
            client.addHeader("Cookie", phpSession);

**Comment by saeed-rz** [comment]
also you can check this issue
https://github.com/android-async-http/android-async-http/issues/978
