### ISSUE TITLE
Empty response body using post request

### ISSUE THREAD

**Issue by fraczekkrzysztof** [android-async-http/android-async-http#1331]
Hi
I'm using version 1.4.9
I make post request and recive empty response body. When I' use postman, I can see the response. 
Here's my code. What do I miss?

```
client.post(getApplicationContext(), requestAddress, stringParams, "application/json", new AsyncHttpResponseHandler() {
                @Override
                public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                    Log.d(TAG, "onSuccess: successfully created event " + new String(responseBody));
                }

                @Override
                public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                    Log.e(TAG, "onFailure: error during creating event on rest", error);
                }
            });
```

**Comment by fraczekkrzysztof** [comment]
It's look like depends on values in header the Body is removed.
For test I hardcoded the value of response body and expose it in different address. Then the response is fine.  But when I using spring-data-rest then my response body is empty.

**Comment by smarek** [comment]
I'm sorry, but spring-data-rest is out of scope for this projects issues. Looks like you're not requesting the URL correctly, or so I guess.
Please let us know in 7 days, or this on hold issue will be closed.
