### ISSUE TITLE
Certificate for <> doesn't match common name of the certificate subject: www.notexist.com

### ISSUE THREAD

**Issue by hejiafeng** [android-async-http/android-async-http#1346]
It's not allowed on Android 6.0.1, but it can be done on higher versions, such as 9.0 and 10.0.

Android 6.0.1 tips

Certificate for <> doesn't match common name of the certificate subject: www.notexist.com

Why is this? Don't know how to solve it?

Looking forward to your reply

thx

**Comment by hejiafeng** [comment]
![20200730174320](https://user-images.githubusercontent.com/23006914/88908285-426e4a00-d28c-11ea-9f7c-b5cef6f5d0e1.png)

Was it caused by changed to CNAME？？？？

**Comment by saeed-rz** [comment]
hi, @hejiafeng 
which version are you using?
do you use Conscrypt?

**Comment by hejiafeng** [comment]
> hi, @hejiafeng
> which version are you using?
> do you use Conscrypt?

I solved it this way.
if (Build.VERSION.SDK_INT > Build.VERSION_CODES.M) {
				socketFactory.setHostnameVerifier(SSLSocketFactory.STRICT_HOSTNAME_VERIFIER);
			}else {
				socketFactory.setHostnameVerifier(SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
			}

**Comment by hejiafeng** [comment]
> hi, @hejiafeng
> which version are you using?
> do you use Conscrypt?

1.4.11
