### ISSUE TITLE
无法解析服务器信息

### ISSUE THREAD

**Issue by BefightingMan** [android-async-http/android-async-http#1348]
我使用的版本是com.loopj.android:android-async-http:1.4.9，但是在Android6.0上一直报错

08-10 09:44:38.709 5697-5930/ceshi.taokeyun.cn D/libc-netbsd: [getaddrinfo]: mtk hostname=114.116.10.175; servname=(null); netid=0; mark=0
08-10 09:44:38.713 5697-5930/ceshi.taokeyun.cn D/libc-netbsd: [getaddrinfo]: mtk hostname=ecs-114-116-10-175.compute.hwclouds-dns.com; servname=(null); netid=0; mark=0
08-10 09:44:38.713 5697-5930/ceshi.taokeyun.cn W/System.err: java.net.UnknownHostException: Unable to resolve host "ecs-114-116-10-175.compute.hwclouds-dns.com": No address associated with hostname

我的服务器IP是114.116.10.175

**Comment by saeed-rz** [comment]
i can understand your language, but if you try connect to server with sni feature, try use this
https://github.com/android-async-http/android-async-http/wiki/Support-SNI-on-lower-android-device
