### ISSUE TITLE
Sending Raw Post Data with RequestParams

### ISSUE THREAD

**Issue by JesseFarebro** [android-async-http/android-async-http#140]
Is there any way currently to send raw post data via RequestParams there are no methods implemented that I see where this is possible. Someone please correct me if I am wrong

**Comment by ChrisJohnsonLevc** [comment]
Jesse Farebro's suggestion to use a string entity helped me significantly.

I needed to supply input to patch Epicor OData with the format:
**{
    "ShortChar01" : "SomeString"
}**

I put all of this (including the braces) in the string entity and called the patch method as below:

asyncHttpClient.patch(null, some_URL, **entity**, "application/json", new JsonHttpResponseHandler(){
   ...
}
It worked like a breeze!

Thank you Jesse
