### ISSUE TITLE
No response called. Nor succes nor failed

### ISSUE THREAD

**Issue by irfanzz** [android-async-http/android-async-http#144]
I put progress dialog in my activity and dismiss it onSuccess and onFailure. There are some cases that ProgressDialog is never dismissed because callback is never called.

**Comment by jagatappv** [comment]
I am having same issue. No success or no failure call.
Any one has solution then please post it...

**Comment by 3ammari** [comment]
I had the same issue , i reviewed my manifest file and found that the

    <uses-permission android:name="android.permission.INTERNET"></uses-permission>
is missing, adding that fixed it for me. the misleading thing is that the application should crash when it request a feature not declared in the manifest.xml but it doesn't, yet works on the emulator perfectly.

**Comment by prabinshrestha** [comment]
guys i think this issue is fixed i just override this method and it works 
    @Override
                public void onFinish() {
              progressDialog.hide();
                    super.onFinish();
          
                }

and its compiled with  compile 'com.loopj.android:android-async-http:1.4.9'
