### ISSUE TITLE
How to solve the problem of CircularRedirectException

### ISSUE THREAD

**Issue by xiedantibu** [android-async-http/android-async-http#145]
How to solve the problem of callback about:org.apache.http.client.CircularRedirectException: Circular redirect to

**Comment by vvasuki** [comment]
I am facing this very problem, but giancar's solution no longer works.. I suspect because of dependency problems:
![image](https://cloud.githubusercontent.com/assets/2664797/24987218/8f750d1e-1fb3-11e7-85b8-a3448e6e1b1f.png)

Can someone suggest a workaround?

**Comment by vvasuki** [comment]
Ah this seems to work: 
`        asyncHttpClient.setEnableRedirects(true, true, true);`

**Comment by Royalone-mobile** [comment]
Ah this seems to work:
asyncHttpClient.setEnableRedirects(true, true, true);

It did worked on my side.
Thank you.
