### ISSUE TITLE
NPE in HttpClient

### ISSUE THREAD

**Issue by ghost** [android-async-http/android-async-http#153]
The first time i install my application on a new device every time this error happens:

12-11 17:26:22.495: W/System.err(29392): java.io.IOException: NPE in HttpClient! Retry nr 5

12-11 17:26:22.495: W/System.err(29392): at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:109)

12-11 17:26:22.495: W/System.err(29392): at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:56)

12-11 17:26:22.495: W/System.err(29392): at com.loopj.android.http.SyncHttpClient.sendRequest(SyncHttpClient.java:70)

12-11 17:26:22.495: W/System.err(29392): at com.loopj.android.http.AsyncHttpClient.get(AsyncHttpClient.java:403)

12-11 17:26:22.495: W/System.err(29392): at com.loopj.android.http.AsyncHttpClient.get(AsyncHttpClient.java:369)

when i restart the application it always works. any hints what I can do against this?

**Comment by eMaringolo** [comment]
I also confirm that when you get a `NullPointerException` inside the `onSuccess(...)` handler, the NPE gets handled by the `onFailure(...)` method. I don't know if this right or wrong, but it is confusing nonetheless.

**Comment by smarek** [comment]
It is kind of confusing, we can add method to handle client-side error handling, so when error happens in library it's handled by `onFailure` but if the error is caught in callback impementation it will get caught in different method, such as `onException`, what do you think @eMaringolo

**Comment by eMaringolo** [comment]
I'm not proficient with exception handling in the context of async/threaded calls. but I don't think that having a third method will help much unless you can get the call stack and debug context where the NPE ocurred, as with any single threaded NPE.
