### ISSUE TITLE
How Do Request a https url

### ISSUE THREAD

**Issue by paulwang2012** [android-async-http/android-async-http#288]
How Do Request a https url

**Comment by mdrabic** [comment]
@korkag I have a stacktrace that is very similar to the one you posted above. How did you find out what the maximum number of concurrent connections are within the SSL library? Can you share your strategy for limiting the number of connections?

**Comment by pedrovarela86** [comment]
Thank you @gahfy your comment is clear and the code Works perfectly.

**Comment by bluebery** [comment]
I'm also seeing the same issue as @korkag 

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
Abort message: 'invalid address or address of corrupt block 0x84280b28 passed to dlfree'
```

in other words...

```
A/libc﹕ invalid address or address of corrupt block 0x631d65a0 passed to dlfree
A/libc﹕ Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 18068 (pool-468-thread)
```

when posting asyncronously to a web server using post(). I am posting ten messages at once, and the issue only appears on Samsung Galaxy devices using android 4.4.

is this related to either of these, perhaps? what is the status of loopj and ALPN support, if this is even related?

https://code.google.com/p/android/issues/detail?id=74964
or
https://github.com/square/okhttp/pull/1474

**Comment by smarek** [comment]
@bluebery cool finding, we will handle this in #834

**Comment by acrolink** [comment]
@gahfy 

Thank you very much for sharing.

**Comment by RealiableLion** [comment]
@gahfy How I can load a keystore so the server can trust me? Because with that method i can't load the client certificate and server-side i get message of empty chain
