### ISSUE TITLE
onSuccess method with response headers not working

### ISSUE THREAD

**Issue by xcode4life** [android-async-http/android-async-http#300]
Hi,

I'm using 1.4.3 library downloaded yesterday and the following method inside AsyncHttpResponseHandler doesn't work:

```
    @Override
    public void onSuccess(int statuscode, Header[] headers, String content) {
        onSuccess(statuscode, content);
    }
```

The onSuccess gets called and works without response header part. When I add the 'Header[] headers' as argument, the following error will occur;'Header cannot be resolved to a type'.

Thank you for your kind assistance and sorry for a newbie question.

**Comment by nahkampf** [comment]
Sorry, another noob here, and posting in a closed issue, but:

I downloaded android-async-http-1.4.6.jar, and followed the example, like so:
```java
package com.foo.bar;
import org.json.*;
import com.foo.bar.Constants;
import com.loopj.android.http.*;

class APICall {
    public void auth(RequestParams params) throws JSONException {
        APIClient.get(Constants.API_AUTH, params, new JsonHttpResponseHandler() {
            @Override
            public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
                // Stuff where I handle a JSONObject
            }
            
            @Override
            public void onSuccess(int statusCode, Header[] headers, JSONArray timeline) {
                // Stuff where I handle a JSONArray
            }
        });
    }
}
```

And I'm getting the same error, "Header cannot be resolved to a type". Can anyone explain to a noob how I can fix that? Is the example just wrong/incompatible with 1.4.6 or am I missing something completely obvious?

**Comment by smarek** [comment]
1.4.3 is old release, you can use 1.4.6 from maven central

**Comment by raul1991** [comment]
I have 1.4.8 , but still i get "Can't resolve org.apache.http.Header" error.

**Comment by mykola-kohut** [comment]
"I have 1.4.8 , but still i get "Can't resolve org.apache.http.Header" error."

+++

**Comment by rome-legacy** [comment]
same here: 1.4.8 and the same error with android studio 1.3.2

**Comment by manojsdoshi** [comment]
same here

**Comment by manojsdoshi** [comment]
Found the solution: 

When the red bulb shows up for suggestions click find jar on the web and download the first one on the list. It will download a jar for you and this fixes the problem. 
It adds the following import "import org.apache.http.Header;"

**Comment by Wayn0** [comment]
Sitting in the same situation if anyone can help

**Comment by rome-legacy** [comment]
as workaround add this dependency to your build.gradle (module: app)

compile "org.apache.httpcomponents:httpcore:4.3.2"

regards
rome

**Comment by Wayn0** [comment]
Thanks, much appreciated. I managed to get it working.

**Comment by BradZzz** [comment]
"Compile org.apache.httpcomponents:httpcore:4.3.2" is the right answer! Thanks man!

**Comment by mugwaneza** [comment]
@rome-legacy's answer works so great
