### ISSUE TITLE
Get progress while downloading image using BinaryHttpResponseHandler.

### ISSUE THREAD

**Issue by yogeshmalpani** [android-async-http/android-async-http#311]
Thanks for such a wonderful library. Just wanted to know is there a way to get the progress or byte size downloaded while downloading big size images/files.
Awaiting response.

Regards,

**Comment by JamesCullum** [comment]
@yassirh 
Just to note: The definition changed to
    @Override
    public void onProgress(long bytesWritten, long totalSize)
