### ISSUE TITLE
How to add a pure JSON as a Parameter

### ISSUE THREAD

**Issue by NemesisDoom** [android-async-http/android-async-http#320]
Hi Guys, been using your library lately, and It's awesome and very simple, but how Do I add a plain JSON String to the parameters?, I'm sending a large amount of data, and have already in a JSON File, don't know how to put it.

**Comment by Navya123** [comment]
what is the context variable being used and what is the need of it?

**Comment by smarek** [comment]
Context is Activity or ApplicationContext (basically ContextWrapper subclass), and it's needed to link the HTTP request with part of application, so it can be cancelled or accounted

**Comment by monkiki** [comment]
Why other post methods does not need the Context?

**Comment by ParitoshVaidya** [comment]
I created simple REST Client as mentioned on [home page](http://loopj.com/android-async-http/). I made this class as singleton. Now I am required to add context. Is there any alternative way? I am thinking of using **Application Context** as there will be only one instance working application wide. Any hints?

**Comment by smarek** [comment]
@ParitoshVaidya what will happen if you provide NULL context? or static context instance, ie. AppContext ?

**Comment by ParitoshVaidya** [comment]
@smarek Application context works fine. I did not try NULL context.

You can check my code at bellow links:

[App.java](https://github.com/ParitoshVaidya/android-snippets/blob/master/app/src/main/java/com/supersnippets/androidsnippets/app/App.java)
[RestClient.java](https://github.com/ParitoshVaidya/android-snippets/blob/master/app/src/main/java/com/supersnippets/androidsnippets/utils/RestClient.java)
