### ISSUE TITLE
often show java.net.SocketException: Connection reset by peer 

### ISSUE THREAD

**Issue by meixililu** [android-async-http/android-async-http#452]
use the newest code,then often show java.net.SocketException: Connection reset by peer,how can i solve the problem?

**Comment by sidpal7747** [comment]
I am facing the same issue but only for the SDK version before LOLLIPOP

**Comment by sidpal7747** [comment]
Is there any other way to update TLS version for an older device by making customization in **SSLSocketFactory** class? And I also noticed that the class has deprecated.

**Comment by saeed-rz** [comment]
thanks @bryosabian . also there is an option to use Conscrypt to solve tls and sni issue for older device
