### ISSUE TITLE
Cannot Connect To Unverified SSL 

### ISSUE THREAD

**Issue by chromestyl** [android-async-http/android-async-http#454]
When trying to connect to https://example.com I get:

`System.err: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate`

The last log then comes from the JsonHttpResponseHandler:

`response body is null, calling onFailure(Throwable, JSONObject)`

any solution?

**Comment by enggazzar** [comment]
AsyncHttpClient client = new AsyncHttpClient(true, 80, 443);
work with me thanks

**Comment by xakiru** [comment]
This is a huge security issue ...
