### ISSUE TITLE
Using AsyncHttpClient from an IntentService

### ISSUE THREAD

**Issue by suneets** [android-async-http/android-async-http#496]
I'm using AsyncHttpClient in a large Android project-- it works great in most cases, except when we need to make network calls from an Intent Service.

In this case-- we actually need to make a synchronous network call but the library doesn't make it easy to do that. 

Also, we use session cookies with our AsyncHttpClient-- we create a static AsyncHttpClient instance and it's used throughout the project, and since we have a session cookie, this is preserved.

So I guess there are two potential solutions:

1) Need a way to create a SyncHttpClient from an instance of AsyncHttpClient so session cookies are preserved

2) Need a way to reliably use AsyncHttpClient in an IntentService

I know some other people have had issues with using this library in an IntentService-- how have you solved it?

**Comment by gsteigert** [comment]
Is there a way to perform synchronous requests with AsyncHttpClient? My handler is created within the main thread, which has a message looper as specified in the error message, but it still cannot be used to perform synchronous requests.

If the only way is to use the SyncHtppClient, then I don't understand why there is a method "setUseSynchronousMode" in AsyncHttpResponseHandler. The response handling strategy should be infered by the client instance being used, or even better, AsyncHttpResponseHandler shouldn't care about it.

**Comment by rodmiranda** [comment]
I was using 1.4.6 with both asynchronous and synchronous calls from a thread.
I had many problems and had to change my layer a couple of times. On one case, I wanted to start an async call from a running thread - I had my reasons - and was getting the exception below:
```
java.lang.IllegalArgumentException: Synchronous ResponseHandler used in AsyncHttpClient. You should create your response handler in a looper thread or use SyncHttpClient instead.
``` 

Then I have overridden the method mentioned in the answer below and all started to work.
http://stackoverflow.com/a/26747653/1713063

**Comment by lbt05** [comment]
In 1.4.6, you can create ResponseHandler with a Looper param...I don't think you need to override the method to make it work.

**Comment by mzeeshanpl** [comment]
aS
