### ISSUE TITLE
How to set uploaded jpg type to be recognised as "image/jpg" instead of "application/octet-stream"

### ISSUE THREAD

**Issue by ariefbayu** [android-async-http/android-async-http#504]
This is my code:

```
File file = new File("sdcard/food.jpg");
params.put("image", file);
```

My problem is, php server received the images as "application/octet-stream" instead of "image/jpg". I need it to be image/jpg as my server guy whitelist uploaded files that have types of "image/jpg", "image/png", etc.

**Comment by kashifandroiddev** [comment]
thankssss @smarek  this help me very much....

**Comment by VannesEventurers** [comment]
Hi @smarek  could you please tell me how to use this code params.put("image", file, "image/jpg") for video? I have use like this  params.put("media", myFile, "video/mp4", "video.mp4"); and params.put("media", myFile, "video/mp4"); but this are all not working. Please suggest me an idea. Thanks in advance
