### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by kamoljan** [android-async-http/android-async-http#505]
Hi guys,

Any plan to support Websockets?

Regards,
Kamol

**Comment by smarek** [comment]
Hello, I'm sorry, but stock HttpClient doesn't provide Websockets support and we've backed away from using OkHttp in further versions.

However I see WebSockets feature implemented in similar library, https://github.com/AsyncHttpClient/async-http-client/tree/master/api/src/main/java/org/asynchttpclient/ws

So I guess, as soon as we rank up higher to HttpClient 4.4 or 4.5 (or start using CloseableHttpClient) we'd be able to provide this feature.

Moving into **future** version, which means, we don't know when we'll be able to implement this yet.

**Comment by smarek** [comment]
Websockets are target of HttpCore 5.0, which we might support, if it ever arrives, see upstream ticket https://issues.apache.org/jira/browse/HTTPCLIENT-973

However due to uncertainity, i'm going to close this ticket for now
