### ISSUE TITLE
Sharing cookies with webviews

### ISSUE THREAD

**Issue by jodaka** [android-async-http/android-async-http#511]
Hello

Not sure if it's the right place to ask, but I need to sync cookies between my async requests and webviews. And I need them to be synced in both ways. 
So ideally I'd just somehow feed android-async-http with android CookieManager, but I can't see easy ways for this. Currently there's interface for persistent cookie storage, but I don't see how it can help with CookieManager integration. 

Any advices would are highly welcome.
I'm also trying to understand if that branch https://github.com/leonardoxh/AsyncOkHttpClient would be easier to use with CookieManager …?

**Comment by rizhilee** [comment]
@trante how to updating PersistentCookieStore？can you show your code?

**Comment by airowe** [comment]
@trante Any code examples on how you accomplished that?
