### ISSUE TITLE
How to properly cancell (all) requests?

### ISSUE THREAD

**Issue by ecdpalma** [android-async-http/android-async-http#522]
I'm downloading large files using FileAsyncHttpResponseHandler but can't cancel with `AsyncHttpClient#cancelAllRequests(true)`. I can't with `AsyncHttpClient#cancelRequests(context, true)` either.

Should I keep reference to the RequestHandle and use it to cancel? Or is it a bug?

**Comment by JamesCullum** [comment]
Same problem here, .cancelAllRequests(true) doesn't stop big file downloads via FileAsyncHttpResponseHandler.
