### ISSUE TITLE
Http request retry number needs to be self-defined  

### ISSUE THREAD

**Issue by ASCE1885** [android-async-http/android-async-http#587]
The current version AsyncHttpClient http request retry no is fixed,defined in AsyncHttpClient.java:
    public static final int DEFAULT_MAX_RETRIES = 5;
    public static final int DEFAULT_RETRY_SLEEP_TIME_MILLIS = 1500;
and somtimes I have to changd the max retry number, but there is no interface,so,maybe it's a good idea to have a public interface for us to change it,thanks a lot

**Comment by juliender** [comment]
The doc says `Sets the maximum number of retries and timeout for a particular Request.`
But the method applies on the `AsyncHttpClient`, not the `RequestHandle`.

Does this means only the next request to be sent with this client will be applied the custom number of retries, the other will be with default retry ?

Concretely I have only one client for my whole project and I want no retry for just 1 request.
Should I just set the max before the request
Or set custom before the request and set back to default after the request ?

Thanks
