### ISSUE TITLE
Insert JSONObject in RequestParams

### ISSUE THREAD

**Issue by crisconru** [android-async-http/android-async-http#624]
I want to send a JSON to my server with a "post", how could insert it?

I try with this but doesn't work, in my server I don't receive a JSON:

``` java
AsyncHttpClient client = new AsyncHttpClient();
RequestParams login = new RequestParams();
JSONObject jlogin = new JSONObject();
        try {
            jlogin.put("id", "3");
            jlogin.put("name", "NAME OF STUDENT");
            jlogin.put("year", "3rd");
            jlogin.put("curriculum", "Arts");
                jlogin.put("birthday", "5/5/1993");
        } catch (JSONException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        login.put("login", jlogin);
        client.post("http://192.168.0.142:8080",login, new JsonHttpResponseHandler(){
            @Override
            public void onSuccess(JSONObject jObject){
                //      
            }   
            @Override
            public void onFailure(Throwable arg0){
                // 
            }
        }); 
```

**Comment by acrolink** [comment]
Any updates as to how to send nested JSON objects within RequestParams ?

**Comment by elliotching** [comment]
at the end I decided to come out on my own algo to solve this problem.
`JsonStreamerEntity` , I have absolutely NO IDEA what is that for and how to use it after google for 10 mins.

so here u go:

```javascript
    private MyEntity jsonData(){
        JSONObject json = new JSONObject();
        try {
            //do create whatever JSONObject you like
            json.put("notification","this and that");
        } catch (JSONException e) {
            e.printStackTrace();
        }
        // Created my own HttpEntity
        MyEntity j = new MyEntity(json.toString()); // remember to convert JSONObject to string
        return j;
```
I'm not sure about **JSONArray** yet, but at least now it is working on my JSONObject.

```javascript
// start post HTTP
final AsyncHttpClient client = new AsyncHttpClient();
client.post( context , url , jsonData() , "application/json" , new MyCustomAsyncHttpRespondHandler() );
```
Oh ya. I don't use RequestParams anymore but HttpEntity. This is because in my case I want to send a pure JSON message only. I don't want any params.
Overridden HttpEntity as followed:
```javascript

    private class MyEntity implements HttpEntity {

        // Size of the byte-array buffer used in I/O streams.
        private final int BUFFER_SIZE = 4096;
        private String json;

        public MyEntity(String jsonstring) {
            json = jsonstring;
        }
        @Override
        public boolean isRepeatable() {
            return false;
        }

        @Override
        public boolean isChunked() {
            return false;
        }

        @Override
        public boolean isStreaming() {
            return false;
        }

        @Override
        public long getContentLength() {
            return -1;
        }

        @Override
        public Header getContentEncoding() {
            return null;
        }

        @Override
        public Header getContentType() {
            return null;
        }

        @Override
        public void consumeContent() throws IOException, UnsupportedOperationException {
        }

        @Override
        public InputStream getContent() throws IOException, UnsupportedOperationException {
            return null;
        }

        @Override
        public void writeTo(final OutputStream out) throws IOException {
            if (out == null) {
                throw new IllegalStateException("Output stream cannot be null.");
            }

            // Record the time when uploading started.
            long now = System.currentTimeMillis();

            OutputStream os = out;

            int[] chararray = new int[json.length()];
            for(int count = 0; count<json.length() ; count++)
                chararray[count] = json.charAt(count);

            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            for(int count = 0; count<json.length() ; count++)
                bos.write(chararray[count]);
            bos.close();
            byte[] arr = bos.toByteArray();

            os.write(arr); // or: bos.writeTo(os);
            os.close();

            System.out.println("bos.toString() = "+new String(bos.toByteArray()));
            os.flush();
            AsyncHttpClient.silentCloseOutputStream(os);
        }
    }
```
Sorry if you are looking for the solution on RequestParams again because for my case is to send a completely pure JSON message only without any params.

**Comment by Schnapse** [comment]
Recently, I also have to send `JSONObject` through HTTP POST request to a web-services (PHP). I used official example which aim to create a `StringEntity` from `JSONObject`. Unfortunately, posted data will be accessible in `php://input` and not `$_POST`.

I just remembered that we can easily send JSONObject thanks to jQuery library and they will be accessible in `$_POST`. In fact, jQuery is converting your JSON to pairs of key/value and send it "normally". So, I quickly wrote a class which convert `JSONObject` to `RequestParams`. Perhaps, it will be more proper  to extend `RequestParams` as `JSONParams` for example and include the conversion logic in.

You can find it [here](https://github.com/Schnapse/json-to-requestparams).

**Comment by avinash8526** [comment]
@crisconru crisconru
Even I was struggling on this, after too much of debugging, the solution came out to be very simple.
In request param object ex:
```
RequestParams params = new RequestParams();
params.setUseJsonStreamer(true);

```
Just set jsonstreamer to true. It works like charm

**Comment by kpstar** [comment]
Hello, Everyone.
I have a serious problem to post a json to server.
The requested module is like this:
<img width="1440" alt="screen shot 2018-03-13 at 5 33 57 pm 1" src="https://user-images.githubusercontent.com/36706893/37410640-00e0b094-27dc-11e8-9bdf-bd8074d5cd26.png">

And my module is ..

JSONObject params = new JSONObject();
        JSONArray nepar = new JSONArray();
        JSONObject paramsone = new JSONObject();
        try {
            params.put("_id",user.id);
            params.put("firstName",user.firstName);
            params.put("lastName",user.lastName);
            params.put("businessName",user.businessName);
            params.put("username",user.username);
            params.put("businessType",user.businessType);
            params.put("phone",user.phone);
            params.put("contactMethod",user.contactMethod);
            params.put("defaultDeal",user.defaultDeal);
            params.put("url",user.url);
            params.put("city",user.city);
            params.put("state",user.state);
            params.put("email",user.email);
            params.put("pwd",user.pwd);
            paramsone.put("user",params.toString());
        } catch (JSONException e) {
            e.printStackTrace();
        }
        try {
            JSONObject jsonnew = new JSONObject(paramsone.toString());
            RequestParams repar = new RequestParams();
            repar.put("user",paramsone.toString());
            repar.put("deviceToken",FirebaseInstanceId.getInstance().getToken());
            repar.put("platform", platform);
            Log.e ("repar",repar.toString());
            post(ServerUrl, repar, new AsyncHttpResponseHandler() {
                @Override
                public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                    try {
                        JSONObject result = new JSONObject(new String(responseBody));
                        Log.e("Success","Successfully done")
                    } catch (JSONException e) {
                        e.printStackTrace();
                    }
                }

                @Override
                public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                    Log.e("Failure","Failed to unregister.");
                }
            });
        } catch (JSONException e) {
            e.printStackTrace();
        }

But it is not working.  Who can solve this? I really want to implement this code. Best Regards.
