### ISSUE TITLE
Get Issue With 1.4.5 only

### ISSUE THREAD

**Issue by ghost** [android-async-http/android-async-http#627]
So everything was working great on version 1.4.4. I will post the code that worked before. We updated to 1.4.5 and this stopped working. I put some break points in and it just seems to jump over the client.get call. Confirmed if we gradle'ed back to 1.4.4 everything works fine. Also dont see any errors in the console or logcat. Any insight? Thanks!

``` java
AsyncHttpClient client = new AsyncHttpClient();
client.get(getResources().getString(R.string.QUERY_URL) + "/Authentication/login?" + params,
    new JsonHttpResponseHandler() {
        @Override
        public void onSuccess(JSONObject jsonObject) {
            String resultMessage;
            resultMessage = jsonObject.optString("resultMessage");
            if (resultMessage.equals("Login Successfull")) {
                // If the Login is successful save off the necessary fields and then go to the managed accounts activity.
                SharedPreferences.Editor e = sharedPreferences.edit();
                progress.dismiss();
                Intent detailIntent = new Intent(getApplicationContext(), MasterActivity.class);
                startActivity(detailIntent);
                finish();
            } else {
                progress.dismiss();
                new AlertDialog.Builder(LoginActivity.this)
                    .setTitle("Login Failed")
                        .setMessage("Please check your username and password")
                        .setIcon(android.R.drawable.ic_dialog_alert)
                        .setNegativeButton("Close", new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialog, int which) {    
                                    }
                            })
                    .show();
            }
        }
        @Override
        public void onFailure(int statusCode, Throwable throwable, JSONObject error) {
            // Display a "Toast" message
            // to announce the failure
            Toast.makeText(getApplicationContext(), "Error: " + statusCode + " " + throwable.getMessage(), Toast.LENGTH_LONG).show();
            progress.dismiss();
        }
    }
);
```

**Comment by kenglang** [comment]
@smarek Thank you, it's working for me :)

**Comment by pmforfull** [comment]
@kenglang can i know what you did please. i tried but no luck.

**Comment by kenglang** [comment]
@smarek I use vesion 1.4.9
My API return json object, i use method onFailure JSONObject your offer and it's working perfect.
Sorry for English !
Below is the code I use:
`String url = ConfigApp.URL_PARENT_MENU;
            AsyncHttpClient client = new AsyncHttpClient();

            client.get(url, new JsonHttpResponseHandler() {
                @Override
                public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
                    // Root JSON in response is an dictionary i.e { "data : [ ... ] }
                    arrPmenu.clear();
                    try {

                        JSONArray jsonarray = response.getJSONArray("MenuParent");

                        for (int i = 0; i < jsonarray.length(); i++) {

                            JSONObject obj = jsonarray.getJSONObject(i);
                            ParrentMenu item = new ParrentMenu();

                            //add object
                            item.setId(obj.getString("CategoryID"));
                            item.setName(obj.getString("CategoryName"));

                            arrPmenu.add(item);
                        }
                        adapterMenu = new AdapterMainMenu(getActivity(), R.layout.item_main_menu, arrPmenu);
                        gridView.setAdapter(adapterMenu);
                        adapterMenu.notifyDataSetChanged();
                        gridView.setEmptyView(myView.findViewById(R.id.emptyElement));
                        progressBar.setVisibility(View.GONE);
                        gridView.setVisibility(View.VISIBLE);
                    } catch (Exception e) {
                        // TODO: handle exception
                    }

                }

                @Override
                public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONObject errorResponse) {
                    Log.d("Mydebug", "onFailure JSONObject");
                    progressBar.setVisibility(View.GONE);
                }

                @Override
                public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONArray errorResponse) {
                    Log.d("Mydebug", "onFailure JSONArray");
                }

                @Override
                public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable) {
                    Log.d("Mydebug", "onFailure String");
                    // called when response HTTP status is "4XX" (eg. 401, 403, 404)

                }

                @Override
                public void onFinish() {
                    Log.d("Mydebug", "--- onFinish ---");
                    super.onFinish();
                    progressBar.setVisibility(View.GONE);
                }

                @Override
                public void onRetry(int retryNo) {
                    Log.d("Mydebug", "--- onRetry ---");
                    super.onRetry(retryNo);
                }
            });`

**Comment by pmforfull** [comment]
@kenglang yes it worked for me too. Just now saw your message. thanks !
