### ISSUE TITLE
GZIP content not inflated

### ISSUE THREAD

**Issue by Ron1969** [android-async-http/android-async-http#641]
When doing a regular Google request (e.g. "https://www.google.com/search?q=github"), the response headers contain content-encoding: gzip but the response is not inflated. The reason for this is that the signature test isInputStreamGZIPCompressed() in AsyncHttpClient.java fails. It tries to read 2 bytes but actually only 1 byte is available in my situation (readStatus is 1). This means that the test fails (readStatus is expected to be 2) though the content is actually valid GZIP.

**Comment by u-drozd** [comment]
Can confirm this still to happen with 1.4.6, http works but it isn't allowed and the response comes with the "REQUEST_DENIED" internal server error.

**Comment by krojew** [comment]
I have the exact same problem. Response is gzip compressed, but not inflated. The response comes from froums.eveonline.com.
