### ISSUE TITLE
how to set addHeader() 

### ISSUE THREAD

**Issue by liuxgchi** [android-async-http/android-async-http#683]
please how to addHeader() when i used new constuctor()  AsyncHttpClient()，i need to setHeader() in my request.please help me!

**Comment by elpoisterio** [comment]
addheader, doesn't seems to work sometimes and request goes without headers. I am facing this problem. If anyone has solved it please help.

![screenshot_20160616_201445](https://cloud.githubusercontent.com/assets/7325457/16121068/6656aa5a-33ff-11e6-8c31-1bee5b692d5f.png)

**Comment by dreamsparkx** [comment]
@elpoisterio Thank you Solved my problem
