### ISSUE TITLE
Crash on cancelling request

### ISSUE THREAD

**Issue by abdullahumer** [android-async-http/android-async-http#686]
I'm not sure if this is a bug or the cancelling method is written intentionally like this. But it was causing crash.

See here: http://stackoverflow.com/q/25666596/1478181

**Comment by perryao** [comment]
When will this version be released to maven central? Ran into this issue myself.

**Comment by smarek** [comment]
@perryao in a week I assume, it's been quite a busy time and I haven't got to push the 1.4.7 to release state
