### ISSUE TITLE
in Release app (proguard config open),PersistentCookieStore can't get stored cookies,

### ISSUE THREAD

**Issue by luotao001** [android-async-http/android-async-http#688]
in Release app (proguard config open),PersistentCookieStore can't get stored cookies,..

``` java
PersistentCookieStore defaultStore = new PersistentCookieStore(BaseApplication.getContext());
client.setCookieStore(defaultStore);
```

in **PersistentCookieStore.java**:

``` java
protected Cookie decodeCookie(String cookieString) {
byte[] bytes = hexStringToByteArray(cookieString);
ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(bytes);
Cookie cookie = null;
try {
    ObjectInputStream objectInputStream = new ObjectInputStream(byteArrayInputStream);
    cookie = ((SerializableCookie) objectInputStream.readObject()).getCookie();
    Utils.showToast("decode cookie complete!");

} catch (Exception e) {

}
return cookie;
}
```

---

if I enable the proguard config, decodeCookie always return null;
and If disable pro guard config,everything is ok

how can I modify the proguard-project.txt??

**Comment by SevanJoe** [comment]
I run into the same problem and @mseanbonner 's solution helps. Thanks. :+1:

**Comment by zjaml** [comment]
I run into the same problem, in addition to @mseanbonner's solution, I had to do the following to make it work, maybe it's caused by certain update. Hope it helps.
-keep class com.loopj.android.** { *; }
-keep interface com.loopj.android.** { *; }
-keep class dalvik.system.**{ *; }
-keep class libcore.**{ *; }

**Comment by YlorD** [comment]
This problem would be there if you set a *PersistentCookieStore* to your AsyncHttpClient and use proguard  and didn't keep the name of serializable class *SerializableCookie*. In fact, just add 
```
-keepnames class * implements java.io.Serializable 
```
or
```
-keep class com.loopj.android.http.SerializableCookie {*;}
```
may solve this problem.
