### ISSUE TITLE
How to add http headers?

### ISSUE THREAD

**Issue by junixapp** [android-async-http/android-async-http#695]
Now I use "AsyncHttpClient.addHeader(key.value)" to add http header,but it seems donot work, becase I 
print log, there is no my header, please help me!

**Comment by 47778971** [comment]
asyncHttpClient.addHeader("auth", "luke");

**Comment by akshayaroraGS** [comment]
when we add headers the parameters is have to null.


client.post(context, url,headers,requestParams, AsyncHttpClient.HEADER_CONTENT_TYPE,new AsyncHttpResponseHandler() {
                    @Override
                    public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                        if(progressDialogFlag){
                            if(dialog.isShowing())
                                dialog.dismiss();
                        }
                        listener.onResponse(requestCode, new String(responseBody));
                    }

                    @Override
                    public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                        if(progressDialogFlag){
                            if(dialog.isShowing())
                                dialog.dismiss();
                        }
                    }
                });
