### ISSUE TITLE
no peer certificate with startssl certificate (validates in browser)

### ISSUE THREAD

**Issue by ghost** [android-async-http/android-async-http#748]
javax.net.ssl.SSLPeerUnverifiedException: No peer certificate

**Comment by blackvvine** [comment]
I'm having the same problem, I'm making a request which I made sure that works fine on Firefox, Chromium and CURL. but when I try to make that in Android Async HTTP library I get a `javax.net.ssl.SSLPeerUnverifiedException: No peer certificate` error.

Bypassing SSL check is not an option, can anyone please help me?
