### ISSUE TITLE
`IllegalArgumentException: Synchronous ResponseHandler used in AsyncHttpClient` after upgrade from 1.4.4 to 1.4.5

### ISSUE THREAD

**Issue by bajtos** [android-async-http/android-async-http#751]
Hi, the change introduced in #507 seems to break our module depending on android-asycn-http, see https://github.com/strongloop/loopback-sdk-android/issues/55.

```
java.lang.IllegalArgumentException: Synchronous ResponseHandler used in AsyncHttpClient. You should create your response handler in a looper thread or use SyncHttpClient instead.
```

This is how I create my handler (a simplified example):

``` java
   class CallbackHandler extends AsyncHttpResponseHandler {
        @Override
        public void onSuccess(int status, Header[] headers, byte[] body) {
          // ...
        }

         @Override
        public void onFailure(int statusCode,
                              org.apache.http.Header[] headers,
                              byte[] responseBody,
                              java.lang.Throwable error) {
          // ...
        }
    }
```

And this is the code using the callback:

``` java
var responseHandler = new CallbackHandler();
client = new HttpClient(context, url); // context and url provided in args
client.request(verb, path, parameters, parameterEncoding, responseHandler);
```

The code works correctly with `v1.4.4` but throws with `v1.4.5`.

Could you please advise whether this is a bug in android-async-http or a problem in my code?

**Comment by bajtos** [comment]
FWIW, our SDK is using AsyncHttpResponseHandler and AsyncHttpClient. However, we are subclassing AsyncHttpClient into a custom class that is called HttpClient, which I think caused some confusion. I have renamed the class to make the code easier to understand, see https://github.com/strongloop/loopback-sdk-android/pull/70

**Comment by smarek** [comment]
Thank you for follow up

**Comment by SolomonBier** [comment]
I'm having a similar issue. See

http://stackoverflow.com/questions/34985255/scheduledthreadpoolexecutor-with-asynchronous-http-client

**Comment by PalakSDarji** [comment]
In my case, I was calling post method from background.

**Comment by shun825** [comment]
Is it true that we shouldn't call post method from background thread?

**Comment by houdangui** [comment]
same with  @PalakSDarji  , I got this issue calling it from a non main thread on android.    Calling it from main thread fixed it
