### ISSUE TITLE
Get Wrong JsonEntity by mistake

### ISSUE THREAD

**Issue by ilioili** [android-async-http/android-async-http#859]
When I want to post Json Data to Server, while something wrong happened.
My code is as follow:

```
    String url = ServerConfig.HOST + "v1/users";
    RequestParams params = new RequestParams();
    params.add("mobile", "1234");
    params.add("code", "1111");
    params.setUseJsonStreamer(true);
    return HttpHelper.executePost(String.class, url, params, callBack);
```

And finally the JsonData is parseed like this {"mobile":"[1234]", "code":"[1111]}"。After a long time debuging, I located my error. And I changed my code as follow.

```
    String url = ServerConfig.HOST + "v1/users";
    RequestParams params = new RequestParams();
    params.put("mobile", "1234");
    params.put("code", "1111");
    params.setUseJsonStreamer(true);
    return HttpHelper.executePost(String.class, url, params, callBack);
```

Then I worked OK now. Becasue "add" methord aims to suppoting mutiple args. And the value is generated as a HashSet. I'd like to suggest that ths code master could add some toast in the JsonStreamerEntity.class (Line 210 [ os.write(escape(value.toString())]). Check out the value type , throw IllegalAugrumentException if necessay.That would be fine!

**Comment by smarek** [comment]
I'm sorry for your troubles, thank you for pointing that out, we've scheduled to rewrite RequestParams completely, and I'll try to clarify such situations better until it's done.
