### ISSUE TITLE
onFailure no being called

### ISSUE THREAD

**Issue by luzianscherrer** [android-async-http/android-async-http#91]
Hi there,

I'm having the problem that when the webservice responds with a 401 error and returns unknown content, neither onSuccess nor onFailure gets called. Shouldn't either of the two always be called? Or am I missing something in my code?

Please note that onSuccess gets called when the webserver responds with a 200 status code. An both onStart and onFinish also get called in any case, failure or not. So the general setup seems to be fine.

``` java
        httpClient.get(myUrl, null, new JsonHttpResponseHandler() {
            @Override
            public void onSuccess(JSONObject response) {
                Log.i(response.toString());
            }

            @Override
            public void onFailure ( Throwable e, JSONObject errorResponse ) {
                String msg = "Object *" + e.toString() + "*" + errorResponse.toString();
                Log.i("onFailure: " + msg);
            }

            @Override
            public void onFailure ( Throwable e, JSONArray errorResponse ) {
                String msg = "Array *" + e.toString() + "*" + errorResponse.toString();
                Log.i("onFailure: " + msg);
            }

            @Override
            public void onFailure ( Throwable e, String errorResponse ) {
                String msg = "String *" + e.toString() + "*" + errorResponse;
                Log.i("onFailure: " + msg);
            }

            @Override
            public void onFinish() {
                Log.i("onFinish");
                }
            }
            @Override
            public void onStart() {
                Log.i("onStart");
            }
        });
```

Thanks for any pointers or ideas!

**Comment by alvintchui** [comment]
Encountered the same issue today. All callback method works except onFailure.
Finally, I had to go for AsyncHttpResponseHandler as a workaround.

**Comment by fcracker79** [comment]
I have solved the problem by overriding ```JsonHttpResponseHandler.onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable)``` in the response handler. Please see ```JsonHttpResponseHandler.onFailure(final int statusCode, final Header[] headers, final byte[] responseBytes, final Throwable throwable)``` method.

**Comment by DerekFangming** [comment]
This issue still exists. This is really not well designed....

**For whomever that is still looking for an work around**

You need to override the other two onFailure method to catch it. One of the three onFailure will get fired but by default, you are provided the one that is not fired during no internet connections. So do this

```
@Override
public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONArray errorResponse) {
	your codd
}

@Override
public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONObject errorResponse) {
	//your code
}
```


Personally, I like to handle all failures in one call back. So use this trick to wire the other two failures to the default onFailure method

```
@Override
public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONArray errorResponse) {
	onFailure(statusCode, headers, throwable.getLocalizedMessage(), throwable);
}

@Override
public void onFailure(int statusCode, Header[] headers, Throwable throwable, JSONObject errorResponse) {
	onFailure(statusCode, headers, throwable.getLocalizedMessage(), throwable);
}
```
