### ISSUE TITLE
AsyncHttpClient is not thread safe

### ISSUE THREAD

**Issue by wikimore** [android-async-http/android-async-http#918]
AsyncHttpClient is not thread safe when multi thread request different Host.

AsyncHttpClient instance have a global `HttpContext` field，this `HttpContext` is share by every thread.

In apache hc AbstractHttpClient.java

```
HttpContext defaultContext = createHttpContext();
if (context == null) {
     execContext = defaultContext;
} else {
      execContext = new DefaultedHttpContext(context, defaultContext);
}
```

DefaultedHttpContext use local context first, and local context is AsyncHttpClient's share global `HttpContext` .

In apache hc DefaultRequestDirector.java

```
// Populate the execution context
context.setAttribute(ExecutionContext.HTTP_TARGET_HOST,target);
```

In apache hc RequestTargetHost.java

```
HttpHost targethost = (HttpHost) context.getAttribute(ExecutionContext.HTTP_TARGET_HOST);
...
...
request.addHeader(HTTP.TARGET_HOST, targethost.toHostString());
```

so when two thread request a.host.com and b.host.com at same time, maybe http header `Host` be changed.

**Comment by MIkeeJY** [comment]
I 've already found this problem...So  how to fix it???

**Comment by smarek** [comment]
@wikimore sorry for getting back to you so much later.
With 1.4.9 version of library, we adopted 4.3.3 upstream version of HttpClient library (and maybe we'll rise the version before release to 4.3.4 or higher)

I suggest we use `PoolingHttpClientConnectionManager` which should maintain thread-safe pool of HttpContext on per-route basis

I'd love your contribution on creating test (in form of *Sample within sample application) on multi-threaded usage of library against multiple hosts (which is not usually the case). Thank you!

**Comment by smarek** [comment]
Sincerely, I've investigated, if we're able to simply switch to `PoolingHttpClientConnectionManager` without changing part of API methods with ability to be overriden. So I'm moving this to 1.5.0 release, where we upgrade to 4.4+ HttpClient hopefully.
